USE [master]
GO

/****** Object:  Database [DoAn_LopHocAo]    Script Date: 3/16/2014 4:50:37 PM ******/
CREATE DATABASE [DoAn_LopHocAo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DoAn_LopHocAo', FILENAME = N'D:\DoAn_LopHocAo.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DoAn_LopHocAo_log', FILENAME = N'D:\DoAn_LopHocAo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DoAn_LopHocAo] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DoAn_LopHocAo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DoAn_LopHocAo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET ARITHABORT OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DoAn_LopHocAo] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DoAn_LopHocAo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DoAn_LopHocAo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DoAn_LopHocAo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DoAn_LopHocAo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DoAn_LopHocAo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DoAn_LopHocAo] SET  MULTI_USER 
GO

ALTER DATABASE [DoAn_LopHocAo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DoAn_LopHocAo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DoAn_LopHocAo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DoAn_LopHocAo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DoAn_LopHocAo] SET  READ_WRITE 
GO


