USE [CongKy]
GO
/****** Object:  StoredProcedure [dbo].[tblChiTietGiaoTrinh_By_PK_iTaiKhoanID_PK_iMonHocID_PK_iGiaoTrinhID]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblChiTietGiaoTrinh_By_PK_iTaiKhoanID_PK_iMonHocID_PK_iGiaoTrinhID]
		@PK_iTaiKhoanID INT
		,@PK_iMonHocID INT
		,@PK_iGiaoTrinhID INT
		,@iTrangThai SMALLINT
		,@newfeed BIT
AS
BEGIN
	SET NOCOUNT ON;
	IF @newfeed = 'TRUE'
		BEGIN
			SELECT b.[PK_iMonHocID], b.[sTenMonHoc], b.[sLinkImage], d.*
			FROM [tblDangKyDayHoc] a inner join [tblMonHoc] b on a.FK_iMonHocID = b.PK_iMonHocID
			inner join [tblGiaoTrinh] c on b.PK_iMonHocID = c.FK_iMonHocID inner join [tblChiTietGiaoTrinh] d on c.FK_iGiaoTrinhID = d.PK_iGiaoTrinhID
			WHERE (@PK_iTaiKhoanID IS NULL OR a.[FK_iTaiKhoanID] = @PK_iTaiKhoanID)
			AND (@PK_iMonHocID IS NULL OR b.PK_iMonHocID = @PK_iMonHocID)
			AND (@PK_iGiaoTrinhID IS NULL OR d.[PK_iGiaoTrinhID] = @PK_iGiaoTrinhID)
			AND DATEPART( wk, d.[tNgayCapNhat]) = DATEPART( wk, GETDATE())
			AND (@iTrangThai IS NULL OR d.[iTrangThai] = @iTrangThai)
			AND (b.[iTrangThai] = 1)
		END
	ELSE
		BEGIN
			SELECT b.[PK_iMonHocID], b.[sTenMonHoc], b.[sLinkImage], d.*
			FROM [tblDangKyDayHoc] a inner join [tblMonHoc] b on a.FK_iMonHocID = b.PK_iMonHocID
			inner join [tblGiaoTrinh] c on b.PK_iMonHocID = c.FK_iMonHocID inner join [tblChiTietGiaoTrinh] d on c.FK_iGiaoTrinhID = d.PK_iGiaoTrinhID
			WHERE (@PK_iTaiKhoanID IS NULL OR a.[FK_iTaiKhoanID] = @PK_iTaiKhoanID)
			AND (@PK_iMonHocID IS NULL OR b.PK_iMonHocID = @PK_iMonHocID)
			AND (@PK_iGiaoTrinhID IS NULL OR d.[PK_iGiaoTrinhID] = @PK_iGiaoTrinhID)
			AND (@iTrangThai IS NULL OR d.[iTrangThai] = @iTrangThai)
			AND (b.[iTrangThai] = 1)
		End
END
GO
/****** Object:  StoredProcedure [dbo].[tblChiTietGiaoTrinh_Delete]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblChiTietGiaoTrinh_Delete]
		@PK_iGiaoTrinhID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblChiTietGiaoTrinh]
	Where
		[PK_iGiaoTrinhID] 	= @PK_iGiaoTrinhID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblChiTietGiaoTrinh_Insert]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblChiTietGiaoTrinh_Insert]
			@sTenBaiHoc	nvarchar(200)
			,@sThongTin	nvarchar(MAX)
			,@sLinkDownload	nvarchar(200)
			,@iType	smallint
			,@iTrangThai	smallint
			,@PK_iMonHocID int
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblChiTietGiaoTrinh]( [sTenBaiHoc]
				,[sThongTin]
				,[sLinkDownload]
				,[iType]
				,[tNgayCapNhat]
				,[iTrangThai]
				)
		
	Values	( @sTenBaiHoc
				,@sThongTin
				,@sLinkDownload
				,@iType
				,Getdate()
				,@iTrangThai
				)

Insert Into [tblGiaoTrinh]( [FK_iMonHocID]
				,[FK_iGiaoTrinhID]
				)
		
	Values	( @PK_iMonHocID
				,SCOPE_IDENTITY()
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblChiTietGiaoTrinh_Search]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblChiTietGiaoTrinh_Search]
			@PK_iGiaoTrinhID	int
			,@sTenBaiHoc	nvarchar(200)
			,@sThongTin	nvarchar(MAX)
			,@sLinkDownload	nvarchar(200)
			,@iType	smallint
			,@tNgayCapNhat	datetime
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iGiaoTrinhID]
				, [sTenBaiHoc]
				, [sThongTin]
				, [sLinkDownload]
				, [iType]
				, [tNgayCapNhat]
				, [iTrangThai]
	From	[tblChiTietGiaoTrinh]
	Where
		(@PK_iGiaoTrinhID is null or [PK_iGiaoTrinhID] 	= @PK_iGiaoTrinhID)
		AND (@sTenBaiHoc is null or [sTenBaiHoc] 	like '%' + @sTenBaiHoc+ '%')
		AND (@sThongTin is null or [sThongTin] 	like '%' + @sThongTin+ '%')
		AND (@sLinkDownload is null or [sLinkDownload] 	like '%' + @sLinkDownload+ '%')
		AND (@iType is null or [iType] 	like '%' + @iType+ '%')
		AND (@tNgayCapNhat is null or [tNgayCapNhat] 	= @tNgayCapNhat)
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblChiTietGiaoTrinh_SelectItem]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblChiTietGiaoTrinh_SelectItem]
		@PK_iGiaoTrinhID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iGiaoTrinhID]
				, [sTenBaiHoc]
				, [sThongTin]
				, [sLinkDownload]
				, [iType]
				, [tNgayCapNhat]
				, [iTrangThai]
	From	[tblChiTietGiaoTrinh]
	Where
		[PK_iGiaoTrinhID] 	= @PK_iGiaoTrinhID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblChiTietGiaoTrinh_SelectList]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblChiTietGiaoTrinh_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iGiaoTrinhID]
				, [sTenBaiHoc]
				, [sThongTin]
				, [sLinkDownload]
				, [iType]
				, [tNgayCapNhat]
				, [iTrangThai]
	From	[tblChiTietGiaoTrinh]
	Order by [PK_iGiaoTrinhID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblChiTietGiaoTrinh_Update]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblChiTietGiaoTrinh_Update]
		@PK_iGiaoTrinhID	int
		,@sTenBaiHoc	nvarchar(200)
		,@sThongTin	nvarchar(MAX)
		,@sLinkDownload	nvarchar(200)
		,@iType	smallint
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblChiTietGiaoTrinh]	SET
		 [sTenBaiHoc] 	= @sTenBaiHoc
		,[sThongTin] 	= @sThongTin
		,[sLinkDownload] 	= @sLinkDownload
		,[iType] 	= @iType
		,[tNgayCapNhat] 	= GETDATE()
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_iGiaoTrinhID] 	= @PK_iGiaoTrinhID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDangKyDayHoc_CheckExists]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDangKyDayHoc_CheckExists]
		@FK_iMonHocID	INT
		,@FK_iTaiKhoanID INT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblDangKyDayHoc]
	 WHERE ([FK_iMonHocID] = @FK_iMonHocID)
		AND ([FK_iTaiKhoanID] = @FK_iTaiKhoanID)
	 )
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblDangKyDayHoc_Delete]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDangKyDayHoc_Delete]
		@FK_iTaiKhoanID	int
		,@FK_iMonHocID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblDangKyDayHoc]
	Where
		[FK_iTaiKhoanID] 	= @FK_iTaiKhoanID
		AND [FK_iMonHocID] 	= @FK_iMonHocID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDangKyDayHoc_Insert]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDangKyDayHoc_Insert]
			@FK_iTaiKhoanID	int
			,@FK_iMonHocID	int
			,@iTrangThai	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblDangKyDayHoc]( [FK_iTaiKhoanID]
				,[FK_iMonHocID]
				,[tNgayDangKy]
				,[iTrangThai]
				)
		
	Values	( @FK_iTaiKhoanID
				,@FK_iMonHocID
				,GETDATE()
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblDangKyDayHoc_Search]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDangKyDayHoc_Search]
			@FK_iTaiKhoanID	int
			,@FK_iMonHocID	int
			,@tNgayDangKy	datetime
			,@iTrangThai	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_iTaiKhoanID]
				, [FK_iMonHocID]
				, [tNgayDangKy]
				, [iTrangThai]
	From	[tblDangKyDayHoc]
	Where
		(@FK_iTaiKhoanID is null or [FK_iTaiKhoanID] 	= @FK_iTaiKhoanID)
		AND (@FK_iMonHocID is null or [FK_iMonHocID] 	= @FK_iMonHocID)
		AND (@tNgayDangKy is null or [tNgayDangKy] 	= @tNgayDangKy)
		AND (@iTrangThai is null or [iTrangThai] 	= @iTrangThai)
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDangKyDayHoc_SelectByFK_iMonHocID]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
	
CREATE PROCEDURE [dbo].[tblDangKyDayHoc_SelectByFK_iMonHocID]
		@FK_iMonHocID	int
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_iTaiKhoanID]
				, [FK_iMonHocID]
				, [tNgayDangKy]
				, [iTrangThai]
	From	[tblDangKyDayHoc]
	Where	FK_iMonHocID	= @FK_iMonHocID
END


GO
/****** Object:  StoredProcedure [dbo].[tblDangKyDayHoc_SelectByFK_iTaiKhoanID]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	
CREATE PROCEDURE [dbo].[tblDangKyDayHoc_SelectByFK_iTaiKhoanID]
		@FK_iTaiKhoanID	int
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_iTaiKhoanID]
				, [FK_iMonHocID]
				, [tNgayDangKy]
				, [iTrangThai]
	From	[tblDangKyDayHoc]
	Where	FK_iTaiKhoanID	= @FK_iTaiKhoanID
END


GO
/****** Object:  StoredProcedure [dbo].[tblDangKyDayHoc_SelectItem]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDangKyDayHoc_SelectItem]
		@FK_iTaiKhoanID	int
		,@FK_iMonHocID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_iTaiKhoanID]
				, [FK_iMonHocID]
				, [tNgayDangKy]
				, [iTrangThai]
	From	[tblDangKyDayHoc]
	Where
		[FK_iTaiKhoanID] 	= @FK_iTaiKhoanID
		AND [FK_iMonHocID] 	= @FK_iMonHocID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDangKyDayHoc_SelectList]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDangKyDayHoc_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_iTaiKhoanID]
				, [FK_iMonHocID]
				, [tNgayDangKy]
				, [iTrangThai]
	From	[tblDangKyDayHoc]
	Order by [FK_iTaiKhoanID], [FK_iMonHocID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDangKyDayHoc_Update]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDangKyDayHoc_Update]
		@FK_iTaiKhoanID	int
		,@FK_iMonHocID	int
		,@iTrangThai	int
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblDangKyDayHoc]	SET
		 [tNgayDangKy] 	= GETDATE()
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[FK_iTaiKhoanID] 	= @FK_iTaiKhoanID
		AND [FK_iMonHocID] 	= @FK_iMonHocID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiaoTrinh_Delete]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiaoTrinh_Delete]
		@FK_iMonHocID	int
		,@FK_iGiaoTrinhID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblGiaoTrinh]
	Where
		[FK_iMonHocID] 	= @FK_iMonHocID
		AND [FK_iGiaoTrinhID] 	= @FK_iGiaoTrinhID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiaoTrinh_Insert]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiaoTrinh_Insert]
			@FK_iMonHocID	int
			,@FK_iGiaoTrinhID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblGiaoTrinh]( [FK_iMonHocID]
				,[FK_iGiaoTrinhID]
				)
		
	Values	( @FK_iMonHocID
				,@FK_iGiaoTrinhID
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblGiaoTrinh_Search]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiaoTrinh_Search]
			@FK_iMonHocID	int
			,@FK_iGiaoTrinhID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_iMonHocID]
				, [FK_iGiaoTrinhID]
	From	[tblGiaoTrinh]
	Where
		(@FK_iMonHocID is null or [FK_iMonHocID] 	= @FK_iMonHocID)
		AND (@FK_iGiaoTrinhID is null or [FK_iGiaoTrinhID] 	= @FK_iGiaoTrinhID)
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiaoTrinh_SelectByFK_iGiaoTrinhID]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
	
CREATE PROCEDURE [dbo].[tblGiaoTrinh_SelectByFK_iGiaoTrinhID]
		@FK_iGiaoTrinhID	int
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_iMonHocID]
				, [FK_iGiaoTrinhID]
	From	[tblGiaoTrinh]
	Where	FK_iGiaoTrinhID	= @FK_iGiaoTrinhID
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiaoTrinh_SelectByFK_iMonHocID]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	
CREATE PROCEDURE [dbo].[tblGiaoTrinh_SelectByFK_iMonHocID]
		@FK_iMonHocID	int
AS
BEGIN
	SET NOCOUNT ON;

	Select 		Top 5 a.[FK_iMonHocID]
				, a.[FK_iGiaoTrinhID]
				, b.sTenBaiHoc
	From	[tblGiaoTrinh] a inner join [tblChiTietGiaoTrinh] b on a.FK_iGiaoTrinhID = b.PK_iGiaoTrinhID
	Where	(FK_iMonHocID	= @FK_iMonHocID)
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiaoTrinh_SelectItem]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiaoTrinh_SelectItem]
		@FK_iMonHocID	int
		,@FK_iGiaoTrinhID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_iMonHocID]
				, [FK_iGiaoTrinhID]
	From	[tblGiaoTrinh]
	Where
		[FK_iMonHocID] 	= @FK_iMonHocID
		AND [FK_iGiaoTrinhID] 	= @FK_iGiaoTrinhID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiaoTrinh_SelectList]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiaoTrinh_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_iMonHocID]
				, [FK_iGiaoTrinhID]
	From	[tblGiaoTrinh]
	Order by [FK_iMonHocID], [FK_iGiaoTrinhID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiaoTrinh_Update]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiaoTrinh_Update]
		@FK_iMonHocID	int
		,@FK_iGiaoTrinhID	int
AS
BEGIN
	SET NOCOUNT ON;
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_Delete]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_Delete]
		@PK_iMonHocID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblMonHoc]
	Where
		[PK_iMonHocID] 	= @PK_iMonHocID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_Insert]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_Insert]
			@sTenMonHoc	nvarchar(100)
			,@sLinkImage nvarchar(200)
			,@iTrangThai	smallint
			,@FK_iTaiKhoanID INT
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblMonHoc]([sTenMonHoc]
				, [sLinkImage]
				,[iTrangThai]
				)
		
	Values	( @sTenMonHoc
				,@sLinkImage
				,@iTrangThai
				)

	Insert Into [tblDangKyDayHoc]( [FK_iTaiKhoanID]
				,[FK_iMonHocID]
				,[tNgayDangKy]
				,[iTrangThai]
				)
		
	Values	( @FK_iTaiKhoanID
				,SCOPE_IDENTITY()
				,GETDATE()
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_Search]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_Search]
			@PK_iMonHocID	int
			,@sTenMonHoc	nvarchar(100)
			,@sLinkImage nvarchar(200)
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iMonHocID]
				, [sTenMonHoc]
				, [iTrangThai]
	From	[tblMonHoc]
	Where
		(@PK_iMonHocID is null or [PK_iMonHocID] 	= @PK_iMonHocID)
		AND (@sTenMonHoc is null or [sTenMonHoc] 	like '%' + @sTenMonHoc+ '%')
		AND (@sLinkImage is null or [sLinkImage] 	like '%' + @sLinkImage+ '%')
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_SelectItem]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_SelectItem]
		@PK_iMonHocID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iMonHocID]
				, [sTenMonHoc]
				, [sLinkImage]
				, [iTrangThai]
	From	[tblMonHoc]
	Where
		[PK_iMonHocID] 	= @PK_iMonHocID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_SelectList]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iMonHocID]
				, [sTenMonHoc]
				, [sLinkImage]
				, [iTrangThai]
	From	[tblMonHoc]
	Order by [PK_iMonHocID] DESC
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_SelectListByFK_iTaiKhoanID]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_SelectListByFK_iTaiKhoanID]
@iTrangThai Smallint
,@FK_iTaiKhoanID varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		a.[PK_iMonHocID]
				, a.[sTenMonHoc]
				, a.[sLinkImage]
				, a.[iTrangThai]
	From	[tblMonHoc] a inner join [tblDangKyDayHoc] b on a.PK_iMonHocID = b.FK_iMonHocID
	Where a.[iTrangThai] = @iTrangThai
	AND b.[FK_iTaiKhoanID] = @FK_iTaiKhoanID
	Order by [PK_iMonHocID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_SelectListByiTrangThai]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_SelectListByiTrangThai]
@iTrangThai Smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iMonHocID]
				, [sTenMonHoc]
				, [sLinkImage]
				, [iTrangThai]
	From	[tblMonHoc]
	Where [iTrangThai] = @iTrangThai
	Order by [PK_iMonHocID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_Update]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_Update]
		@PK_iMonHocID	int
		,@sTenMonHoc	nvarchar(100)
		,@sLinkImage nvarchar(200)
		,@iTrangThai	smallint
		,@FK_iTaiKhoanID int
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblMonHoc]	SET
		 [sTenMonHoc] 	= @sTenMonHoc
		 ,[sLinkImage] 	= @sLinkImage
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_iMonHocID] 	= @PK_iMonHocID
		
		
	UPDATE [tblDangKyDayHoc]	SET
		[FK_iTaiKhoanID] = @FK_iTaiKhoanID
		,[tNgayDangKy] 	= GETDATE()
		,[iTrangThai] 	= @iTrangThai
	WHERE  [FK_iMonHocID] 	= @PK_iMonHocID
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_CheckExists_sEmail]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_CheckExists_sEmail]
		@sEmail	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblTaiKhoan] WHERE [sEmail] = @sEmail)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_CheckExists_sTenDangNhap]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_CheckExists_sTenDangNhap]
		@sTenDangNhap	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblTaiKhoan] WHERE [sTenDangNhap] = @sTenDangNhap)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_Delete]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_Delete]
		@PK_iTaiKhoanID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblTaiKhoan]
	Where
		[PK_iTaiKhoanID] 	= @PK_iTaiKhoanID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_Insert]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_Insert]
			@sTenDangNhap	varchar(50)
			,@sMatKhau	varchar(50)
			,@sHoTen	nvarchar(50)
			,@sEmail	varchar(50)
			,@sDiaChi	nvarchar(500)
			,@sSoDienThoai	varchar(13)
			,@sLinkAvatar	nvarchar(500)
			,@tNgaySinh	datetime
			,@iQuyenHan	smallint
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblTaiKhoan]( [sTenDangNhap]
				,[sMatKhau]
				,[sHoTen]
				,[sEmail]
				,[sDiaChi]
				,[sSoDienThoai]
				,[sLinkAvatar]
				,[tNgaySinh]
				,[tNgayDangKy]
				,[iQuyenHan]
				,[iTrangThai]
				)
		
	Values	( @sTenDangNhap
				,@sMatKhau
				,@sHoTen
				,@sEmail
				,@sDiaChi
				,@sSoDienThoai
				,@sLinkAvatar
				,@tNgaySinh
				,GETDATE()
				,@iQuyenHan
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_Login]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	12/05/2014 02:03
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_Login]
		@sTenDangNhap varchar(50)	
		,@sMatKhau  varchar(50)	
		,@iQuyenHan smallint
		,@iTrangThai smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select * From	[tblTaiKhoan]
	Where [sTenDangNhap] 	= @sTenDangNhap
			AND [sMatKhau] = @sMatKhau
			AND [iQuyenHan] = @iQuyenHan
			AND [iTrangThai] = @iTrangThai
	Select [sTenDangNhap] from [tblTaiKhoan] where [sTenDangNhap] = @sTenDangNhap
	Select [iQuyenHan] from [tblTaiKhoan] where [sTenDangNhap] = @sTenDangNhap AND [iQuyenHan] = @iQuyenHan
	Select [iTrangThai] from [tblTaiKhoan] where [sTenDangNhap] = @sTenDangNhap AND [iTrangThai] = @iTrangThai
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_Search]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_Search]
			@PK_iTaiKhoanID	int
			,@sTenDangNhap	varchar(50)
			,@sMatKhau	varchar(50)
			,@sHoTen	nvarchar(50)
			,@sEmail	varchar(50)
			,@sDiaChi	nvarchar(500)
			,@sSoDienThoai	varchar(13)
			,@sLinkAvatar	nvarchar(500)
			,@tNgaySinh	datetime
			,@tNgayDangKy	datetime
			,@iQuyenHan	smallint
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iTaiKhoanID]
				, [sTenDangNhap]
				, [sMatKhau]
				, [sHoTen]
				, [sEmail]
				, [sDiaChi]
				, [sSoDienThoai]
				, [sLinkAvatar]
				, [tNgaySinh]
				, [tNgayDangKy]
				, [iQuyenHan]
				, [iTrangThai]
	From	[tblTaiKhoan]
	Where
		(@PK_iTaiKhoanID is null or [PK_iTaiKhoanID] 	= @PK_iTaiKhoanID)
		AND (@sTenDangNhap is null or [sTenDangNhap] 	like '%' + @sTenDangNhap+ '%')
		AND (@sMatKhau is null or [sMatKhau] 	like '%' + @sMatKhau+ '%')
		AND (@sHoTen is null or [sHoTen] 	like '%' + @sHoTen+ '%')
		AND (@sEmail is null or [sEmail] 	like '%' + @sEmail+ '%')
		AND (@sDiaChi is null or [sDiaChi] 	like '%' + @sDiaChi+ '%')
		AND (@sSoDienThoai is null or [sSoDienThoai] 	like '%' + @sSoDienThoai+ '%')
		AND (@sLinkAvatar is null or [sLinkAvatar] 	like '%' + @sLinkAvatar+ '%')
		AND (@tNgaySinh is null or [tNgaySinh] 	= @tNgaySinh)
		AND (@tNgayDangKy is null or [tNgayDangKy] 	= @tNgayDangKy)
		AND (@iQuyenHan is null or [iQuyenHan] 	like '%' + @iQuyenHan+ '%')
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_SelectItem]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_SelectItem]
		@PK_iTaiKhoanID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iTaiKhoanID]
				, [sTenDangNhap]
				, [sMatKhau]
				, [sHoTen]
				, [sEmail]
				, [sDiaChi]
				, [sSoDienThoai]
				, [sLinkAvatar]
				, [tNgaySinh]
				, [tNgayDangKy]
				, [iQuyenHan]
				, [iTrangThai]
	From	[tblTaiKhoan]
	Where
		[PK_iTaiKhoanID] 	= @PK_iTaiKhoanID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_SelectItemByPK_iTaiKhoanID]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	12/05/2014 02:03
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_SelectItemByPK_iTaiKhoanID]
		@PK_iTaiKhoanID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iTaiKhoanID]
				, [sTenDangNhap]
				, [sMatKhau]
				, [sHoTen]
				, [sEmail]
				, [sDiaChi]
				, [sSoDienThoai]
				, [sLinkAvatar]
				, [tNgaySinh]
				, [tNgayDangKy]
				, [iQuyenHan]
				, [iTrangThai]
	From	[tblTaiKhoan]
	Where
		[PK_iTaiKhoanID] 	= @PK_iTaiKhoanID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_SelectItemBysTenDangNhap]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	12/05/2014 02:03
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_SelectItemBysTenDangNhap]
		@sTenDangNhap	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iTaiKhoanID]
				, [sTenDangNhap]
				, [sMatKhau]
				, [sHoTen]
				, [sEmail]
				, [sDiaChi]
				, [sSoDienThoai]
				, [sLinkAvatar]
				, [tNgaySinh]
				, [tNgayDangKy]
				, [iQuyenHan]
				, [iTrangThai]
	From	[tblTaiKhoan]
	Where
		[sTenDangNhap] 	= @sTenDangNhap
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_SelectList]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iTaiKhoanID]
				, [sTenDangNhap]
				, [sMatKhau]
				, [sHoTen]
				, [sEmail]
				, [sDiaChi]
				, [sSoDienThoai]
				, [sLinkAvatar]
				, [tNgaySinh]
				, [tNgayDangKy]
				, [iQuyenHan]
				, [iTrangThai]
	From	[tblTaiKhoan]
	Order by [PK_iTaiKhoanID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_SelectListByiQuyenHan]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	12/05/2014 02:03
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_SelectListByiQuyenHan]
@iQuyenHan smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iTaiKhoanID]
				, [sTenDangNhap]
				, [sMatKhau]
				, [sHoTen]
				, [sEmail]
				, [sDiaChi]
				, [sSoDienThoai]
				, [sLinkAvatar]
				, [tNgaySinh]
				, [tNgayDangKy]
				, [iQuyenHan]
				, [iTrangThai]
	From	[tblTaiKhoan]
	Where [iQuyenHan] = @iQuyenHan
	Order by [PK_iTaiKhoanID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_SelectListByiQuyenHan_iTrangThai]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	12/05/2014 02:03
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_SelectListByiQuyenHan_iTrangThai]
@iQuyenHan smallint
,@iTrangThai smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_iTaiKhoanID]
				, [sTenDangNhap]
				, [sMatKhau]
				, [sHoTen]
				, [sEmail]
				, [sDiaChi]
				, [sSoDienThoai]
				, [sLinkAvatar]
				, [tNgaySinh]
				, [tNgayDangKy]
				, [iQuyenHan]
				, [iTrangThai]
	From	[tblTaiKhoan]
	Where (@iQuyenHan IS NULL OR [iQuyenHan] = @iQuyenHan)
	AND (@iTrangThai IS NULL OR [iTrangThai] = @iTrangThai)
	Order by [PK_iTaiKhoanID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblTaiKhoan_Update]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	CongKyHero
-- Create date:	23/05/2014 21:08
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblTaiKhoan_Update]
		@PK_iTaiKhoanID	int
		,@sTenDangNhap	varchar(50)
		,@sMatKhau	varchar(50)
		,@sHoTen	nvarchar(50)
		,@sEmail	varchar(50)
		,@sDiaChi	nvarchar(500)
		,@sSoDienThoai	varchar(13)
		,@sLinkAvatar	nvarchar(500)
		,@tNgaySinh	datetime
		,@iQuyenHan	smallint
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblTaiKhoan]	SET
		 [sTenDangNhap] 	= @sTenDangNhap
		,[sMatKhau] 	= @sMatKhau
		,[sHoTen] 	= @sHoTen
		,[sEmail] 	= @sEmail
		,[sDiaChi] 	= @sDiaChi
		,[sSoDienThoai] 	= @sSoDienThoai
		,[sLinkAvatar] 	= @sLinkAvatar
		,[tNgaySinh] 	= @tNgaySinh
		,[tNgayDangKy] 	= GETDATE()
		,[iQuyenHan] 	= @iQuyenHan
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_iTaiKhoanID] 	= @PK_iTaiKhoanID
		
END


GO
/****** Object:  Table [dbo].[tblChiTietGiaoTrinh]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblChiTietGiaoTrinh](
	[PK_iGiaoTrinhID] [int] IDENTITY(1,1) NOT NULL,
	[sTenBaiHoc] [nvarchar](200) NOT NULL,
	[sThongTin] [nvarchar](max) NOT NULL,
	[sLinkDownload] [nvarchar](200) NOT NULL,
	[iType] [smallint] NOT NULL,
	[tNgayCapNhat] [datetime] NOT NULL,
	[iTrangThai] [smallint] NOT NULL,
 CONSTRAINT [PK_tblGiaoTrinh] PRIMARY KEY CLUSTERED 
(
	[PK_iGiaoTrinhID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tblDangKyDayHoc]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblDangKyDayHoc](
	[FK_iTaiKhoanID] [int] NOT NULL,
	[FK_iMonHocID] [int] NOT NULL,
	[tNgayDangKy] [datetime] NOT NULL,
	[iTrangThai] [int] NOT NULL,
 CONSTRAINT [PK_tblDangKyDayHoc] PRIMARY KEY CLUSTERED 
(
	[FK_iTaiKhoanID] ASC,
	[FK_iMonHocID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tblGiaoTrinh]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblGiaoTrinh](
	[FK_iMonHocID] [int] NOT NULL,
	[FK_iGiaoTrinhID] [int] NOT NULL,
 CONSTRAINT [PK_GiaoTrinh] PRIMARY KEY CLUSTERED 
(
	[FK_iMonHocID] ASC,
	[FK_iGiaoTrinhID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tblMonHoc]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblMonHoc](
	[PK_iMonHocID] [int] IDENTITY(1,1) NOT NULL,
	[sTenMonHoc] [nvarchar](100) NOT NULL,
	[sLinkImage] [nvarchar](200) NULL,
	[iTrangThai] [smallint] NOT NULL,
 CONSTRAINT [PK_tblMonHoc] PRIMARY KEY CLUSTERED 
(
	[PK_iMonHocID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tblTaiKhoan]    Script Date: 31/05/2014 13:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblTaiKhoan](
	[PK_iTaiKhoanID] [int] IDENTITY(1,1) NOT NULL,
	[sTenDangNhap] [varchar](50) NOT NULL,
	[sMatKhau] [varchar](50) NOT NULL,
	[sHoTen] [nvarchar](50) NOT NULL,
	[sEmail] [varchar](50) NOT NULL,
	[sDiaChi] [nvarchar](500) NOT NULL,
	[sSoDienThoai] [varchar](13) NOT NULL,
	[sLinkAvatar] [nvarchar](500) NOT NULL,
	[tNgaySinh] [datetime] NULL,
	[tNgayDangKy] [datetime] NOT NULL,
	[iQuyenHan] [smallint] NOT NULL,
	[iTrangThai] [smallint] NOT NULL,
 CONSTRAINT [PK_tblTaiKhoan] PRIMARY KEY CLUSTERED 
(
	[PK_iTaiKhoanID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[tblChiTietGiaoTrinh] ON 

GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (1, N'Tìm hiểu về công nghệ ASP.NET', N'asp.net là của microsoft', N'../Upload/Ebook/Mo_Hinh_Ket_Noi_CSDL.pdf', 1, CAST(0x0000A339010973DC AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (2, N'Tìm hiểu về chủ tịch Hồ Chí Minh', N'tt', N'../Upload/Video/movie.mp4', 1, CAST(0x0000A3390119043C AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (3, N'Chiến tranh thế giới thứ 1', N'Chiến tranh thế giới thứ 1', N'../Upload/Video/movie.mov', 1, CAST(0x0000A339011B2078 AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (4, N'Chiến tranh thế giới thứ 2', N'Chiến tranh thế giới thứ 2', N'../Upload/Video/movie.wmv', 1, CAST(0x0000A339011B3C98 AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (5, N'Chiến tranh thế giới thứ 3', N'Chiến tranh thế giới thứ 3', N'../Upload/Ebook/Mo_Hinh_Ket_Noi_CSDL.pdf', 2, CAST(0x0000A2FC011B44CC AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (6, N'Kiến trúc máy tính là gì?', N'Tìm hiểu về khái niệm', N'../Upload/Ebook/KienTrucMayTinh.pdf', 2, CAST(0x0000A33B0115C1C5 AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (7, N'SQL Server Đề cương môn học', N'Đề cương', N'../Upload/Ebook/SQLServer_DeCuongMonHoc.pdf', 2, CAST(0x0000A35A01170A0A AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (8, N'SQL Server Chương 1', N'SQL Server là một hệ thống quản lý cơ sở dữ liệu (Relational Database Management System (RDBMS) ) sử dụng Transact-SQL để trao đổi dữ liệu giữa Client computer và SQL Server computer. Một RDBMS bao gồm databases, database engine và các ứng dụng dùng để quản lý dữ liệu và các bộ phận khác nhau trong RDBMS.', N'../Upload/Ebook/SQLServer_Chuong1_GioiThieu.pdf', 2, CAST(0x0000A2FE0117531C AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (9, N'Quản trị mạng là gì?', N'Công việc chính của quản trị mạng là j?
+ Tùy theo mức độ và mô hình mạng của cty mà công việc của QTM sẽ có mức độ khác nhau. 
- Đảm bảo hệ thống vận hành 1 cách trơn chu và thông suốt " Internet, mail, web, dns, dhcp, database........"
- Có khả năng phân tích., thiết lập, update các mô hình network mới cho phù hợp với mô hình của cty. 
note: "Nhiều anh làm QTM ở những cty nhỏ công việc chính cũng chỉ hơn mấy bác làm hardware một tí."
Mình cần nắm phần nào kỹ nhất ??
1: Kiến thức cơ bản, 
- học mạng khác với học phần mềm " ko thể lựa chọn ngôn ngữ lập trình mà học như phần mềm được".
2: Bạn phải nắm rõ tất cả mọi ứng dụng trên hệ thống.', N'../Upload/Ebook/QuanTriMang_Cache Injection.pdf', 2, CAST(0x0000A2C3011F20B3 AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (10, N'Java Core Chương 1', N'Java là một công nghệ xây dựng các ứng dụng phần mềm có vị trí rất lớn trong những năm cuối thế kỉ 20, đầu thế kỉ 21. Nó được coi là công nghệ mang tính cách mạng và khả thi nhất trong việc tạo ra các ứng dụng có khả năng chạy thống nhất trên nhiều nền tảng mà chỉ cần biên dịch một lần.', N'../Upload/Ebook/Java_Core_1.pdf', 2, CAST(0x0000A33B012123E8 AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (11, N'Giới thiệu về Lập trình hướng đối tượng', N'Lập trình hướng đối tượng (gọi tắt là OOP, từ chữ Anh ngữ object-oriented programming), hay còn gọi là lập trình định hướng đối tượng, là kĩ thuật lập trình hỗ trợ công nghệ đối tượng. OOP được xem là giúp tăng năng suất, đơn giản hóa độ phức tạp khi bảo trì cũng như mở rộng phần mềm bằng cách cho phép lập trình viên tập trung vào các đối tượng phần mềm ở bậc cao hơn. Ngoài ra, nhiều người còn cho rằng OOP dễ tiếp thu hơn cho những người mới học về lập trình hơn là các phương pháp trước đó.', N'../Upload/Ebook/LapTrinhHuongDoiTuong.pdf', 2, CAST(0x0000A33C0017F6A2 AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (1011, N'Java Core Chương 2', N'Java là một công nghệ xây dựng các ứng dụng phần mềm có vị trí rất lớn trong những năm cuối thế kỉ 20, đầu thế kỉ 21. Nó được coi là công nghệ mang tính cách mạng và khả thi nhất trong việc tạo ra các ứng dụng có khả năng chạy thống nhất trên nhiều nền tảng mà chỉ cần biên dịch một lần.', N'../Upload/Ebook/Java_Core_2.pdf', 2, CAST(0x0000A33B012123E8 AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (1012, N'Java Core Chương 5', N'Java là một công nghệ xây dựng các ứng dụng phần mềm có vị trí rất lớn trong những năm cuối thế kỉ 20, đầu thế kỉ 21. Nó được coi là công nghệ mang tính cách mạng và khả thi nhất trong việc tạo ra các ứng dụng có khả năng chạy thống nhất trên nhiều nền tảng mà chỉ cần biên dịch một lần.', N'../Upload/Ebook/Java_Core_5.pdf', 2, CAST(0x0000A33B012123E8 AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (1019, N'Mã nguồn mở', N'Linux', N'../Upload/Ebook/MaNguonMo_LinuxKernel.pdf', 2, CAST(0x0000A3F400000000 AS DateTime), 1)
GO
INSERT [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID], [sTenBaiHoc], [sThongTin], [sLinkDownload], [iType], [tNgayCapNhat], [iTrangThai]) VALUES (1021, N'Ubuntu là gì?', N'Ubuntu', N'../Upload/Ebook/MaNguonMo_Ubuntu.pdf', 2, CAST(0x0000A30200000000 AS DateTime), 1)
GO
SET IDENTITY_INSERT [dbo].[tblChiTietGiaoTrinh] OFF
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (2, 9, CAST(0x0000A33C00B7FFA9 AS DateTime), 1)
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (4, 11, CAST(0x0000A33C00C8FA98 AS DateTime), 1)
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (5, 5, CAST(0x0000A32200000000 AS DateTime), 1)
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (6, 1, CAST(0x0000A33C00DE82E0 AS DateTime), 1)
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (6, 7, CAST(0x0000A33C00E114A2 AS DateTime), 1)
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (7, 10, CAST(0x0000A33C00C8D955 AS DateTime), 1)
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (17, 1, CAST(0x0000A33C00D0198F AS DateTime), 1)
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (17, 6, CAST(0x0000A33B00CFD087 AS DateTime), 1)
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (17, 7, CAST(0x0000A33C00E1074C AS DateTime), 1)
GO
INSERT [dbo].[tblDangKyDayHoc] ([FK_iTaiKhoanID], [FK_iMonHocID], [tNgayDangKy], [iTrangThai]) VALUES (17, 8, CAST(0x0000A2C600000000 AS DateTime), 1)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (1, 11)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (6, 1019)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (6, 1021)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (7, 2)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (7, 3)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (7, 4)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (7, 5)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (8, 6)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (9, 7)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (9, 8)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (10, 9)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (11, 10)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (11, 1011)
GO
INSERT [dbo].[tblGiaoTrinh] ([FK_iMonHocID], [FK_iGiaoTrinhID]) VALUES (11, 1012)
GO
SET IDENTITY_INSERT [dbo].[tblMonHoc] ON 

GO
INSERT [dbo].[tblMonHoc] ([PK_iMonHocID], [sTenMonHoc], [sLinkImage], [iTrangThai]) VALUES (1, N'Lập trình hướng đối tượng', N'../Upload/Images/oop.png', 1)
GO
INSERT [dbo].[tblMonHoc] ([PK_iMonHocID], [sTenMonHoc], [sLinkImage], [iTrangThai]) VALUES (5, N'Lập trình Web', N'../Upload/Images/web.jpg', 1)
GO
INSERT [dbo].[tblMonHoc] ([PK_iMonHocID], [sTenMonHoc], [sLinkImage], [iTrangThai]) VALUES (6, N'Mã nguồn mở', N'../Upload/Images/open_source.jpg', 1)
GO
INSERT [dbo].[tblMonHoc] ([PK_iMonHocID], [sTenMonHoc], [sLinkImage], [iTrangThai]) VALUES (7, N'Tư tưởng Hồ Chí Minh', N'../Upload/Images/TTHCM.jpg', 1)
GO
INSERT [dbo].[tblMonHoc] ([PK_iMonHocID], [sTenMonHoc], [sLinkImage], [iTrangThai]) VALUES (8, N'Kiến trúc máy tính', N'../Upload/Images/kientrucmaytinh.gif', 1)
GO
INSERT [dbo].[tblMonHoc] ([PK_iMonHocID], [sTenMonHoc], [sLinkImage], [iTrangThai]) VALUES (9, N'SQL Server', N'../Upload/Images/sqlserver.jpg', 1)
GO
INSERT [dbo].[tblMonHoc] ([PK_iMonHocID], [sTenMonHoc], [sLinkImage], [iTrangThai]) VALUES (10, N'Quản trị mạng', N'../Upload/Images/quantrimang.jpg', 1)
GO
INSERT [dbo].[tblMonHoc] ([PK_iMonHocID], [sTenMonHoc], [sLinkImage], [iTrangThai]) VALUES (11, N'Java', N'../Upload/Images/java.jpg', 1)
GO
SET IDENTITY_INSERT [dbo].[tblMonHoc] OFF
GO
SET IDENTITY_INSERT [dbo].[tblTaiKhoan] ON 

GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (1, N'admin', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Đào Mạnh Kỳ', N'daomanhky@gmail.com', N'Hà Nội', N'1234567890', N'~/Upload/Avatar/Default.jpg', CAST(0x000083C800000000 AS DateTime), CAST(0x0000A32E014C9694 AS DateTime), 1, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (2, N'hoapc', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Phạm Công Hòa', N'conghoaf1@gmail.com', N'Nam Định', N'0123456789', N'~/Upload/Avatar/Default.jpg', CAST(0x0000A32B00000000 AS DateTime), CAST(0x0000A32E014C9694 AS DateTime), 2, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (3, N'xuantt', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Trịnh Thị Xuân', N'trinhxuan@gmal.com', N'HN', N'1', N'~/Upload/Avatar/Default.jpg', CAST(0x000083C300000000 AS DateTime), CAST(0x0000A32E01688EBC AS DateTime), 2, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (4, N'longdt', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Đinh Tuấn Long', N'dinhtuanlong@gmail.com', N'Vĩnh Phúc', N'2412516165', N'~/Upload/Avatar/Default.jpg', CAST(0x0000843A00000000 AS DateTime), CAST(0x0000A32E016D9FA6 AS DateTime), 2, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (5, N'tungtt', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Thái Thanh Tùng', N'tttung@rocketmail.com', N'Hà Nội', N'12345678901', N'~/Upload/Avatar/Default.jpg', CAST(0x0000854100000000 AS DateTime), CAST(0x0000A32E016EE118 AS DateTime), 2, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (6, N'sinhvien', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Sinh Viên', N'abc1@yahoo.com', N'Hà Nội', N'123456', N'~/Upload/Avatar/Default.jpg', CAST(0x0000854600000000 AS DateTime), CAST(0x0000A32E016F344C AS DateTime), 3, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (7, N'huynt', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Nguyễn Thành Huy', N'huynt@live.co.uk', N'', N'', N'~/Upload/Avatar/Default.jpg', NULL, CAST(0x0000A3320185B21E AS DateTime), 2, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (8, N'anhnd', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Nguyễn Đức Anh', N'anhnd@yahoo.com', N'Hà Nội', N'1234567890', N'~/Upload/Avatar/Default.jpg', CAST(0x0000A33400CC630C AS DateTime), CAST(0x0000A33400CD04B0 AS DateTime), 3, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (9, N'daomanhky', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Công Kỳ Hero', N'congky@gmail.com', N'', N'', N'~/Upload/Avatar/Default.jpg', NULL, CAST(0x0000A33C00B7D36E AS DateTime), 3, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (13, N'minhbv', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Bùi Văn Minh', N'minh.buivanminh@gmail.com', N'Vĩnh Phúc', N'1000000000', N'~/Upload/Avatar/Default.jpg', NULL, CAST(0x0000A33C00C40D87 AS DateTime), 3, 1)
GO
INSERT [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID], [sTenDangNhap], [sMatKhau], [sHoTen], [sEmail], [sDiaChi], [sSoDienThoai], [sLinkAvatar], [tNgaySinh], [tNgayDangKy], [iQuyenHan], [iTrangThai]) VALUES (17, N'giangvien', N'40bd001563085fc35165329ea1ff5c5ecbdbbeef', N'Giảng Viên', N'giangvien@gmail.com', N'Hà Nội', N'12345678901', N'~/Upload/Avatar/Default.jpg', CAST(0x0000854100000000 AS DateTime), CAST(0x0000A32E016EE118 AS DateTime), 2, 1)
GO
SET IDENTITY_INSERT [dbo].[tblTaiKhoan] OFF
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UQ_tblTaiKhoan_sEmail]    Script Date: 31/05/2014 13:53:47 ******/
ALTER TABLE [dbo].[tblTaiKhoan] ADD  CONSTRAINT [UQ_tblTaiKhoan_sEmail] UNIQUE NONCLUSTERED 
(
	[sEmail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UQ_tblTaiKhoan_sTenDangNhap]    Script Date: 31/05/2014 13:53:47 ******/
ALTER TABLE [dbo].[tblTaiKhoan] ADD  CONSTRAINT [UQ_tblTaiKhoan_sTenDangNhap] UNIQUE NONCLUSTERED 
(
	[sTenDangNhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblDangKyDayHoc] ADD  CONSTRAINT [DF_tblDangKyDayHoc_tNgayDangKy]  DEFAULT (getdate()) FOR [tNgayDangKy]
GO
ALTER TABLE [dbo].[tblMonHoc] ADD  CONSTRAINT [DF_tblMonHoc_iTrangThai]  DEFAULT ((1)) FOR [iTrangThai]
GO
ALTER TABLE [dbo].[tblTaiKhoan] ADD  CONSTRAINT [DF_tblTaiKhoan_tNgayDangKy]  DEFAULT (getdate()) FOR [tNgayDangKy]
GO
ALTER TABLE [dbo].[tblTaiKhoan] ADD  CONSTRAINT [DF_tblTaiKhoan_iQuyenHan]  DEFAULT ((0)) FOR [iQuyenHan]
GO
ALTER TABLE [dbo].[tblTaiKhoan] ADD  CONSTRAINT [DF_tblTaiKhoan_iTrangThai]  DEFAULT ((0)) FOR [iTrangThai]
GO
ALTER TABLE [dbo].[tblDangKyDayHoc]  WITH CHECK ADD  CONSTRAINT [FK_tblDangKyDayHoc_tblMonHoc] FOREIGN KEY([FK_iMonHocID])
REFERENCES [dbo].[tblMonHoc] ([PK_iMonHocID])
GO
ALTER TABLE [dbo].[tblDangKyDayHoc] CHECK CONSTRAINT [FK_tblDangKyDayHoc_tblMonHoc]
GO
ALTER TABLE [dbo].[tblDangKyDayHoc]  WITH CHECK ADD  CONSTRAINT [FK_tblDangKyDayHoc_tblTaiKhoan] FOREIGN KEY([FK_iTaiKhoanID])
REFERENCES [dbo].[tblTaiKhoan] ([PK_iTaiKhoanID])
GO
ALTER TABLE [dbo].[tblDangKyDayHoc] CHECK CONSTRAINT [FK_tblDangKyDayHoc_tblTaiKhoan]
GO
ALTER TABLE [dbo].[tblGiaoTrinh]  WITH CHECK ADD  CONSTRAINT [FK_GiaoTrinh_tblChiTietGiaoTrinh] FOREIGN KEY([FK_iGiaoTrinhID])
REFERENCES [dbo].[tblChiTietGiaoTrinh] ([PK_iGiaoTrinhID])
GO
ALTER TABLE [dbo].[tblGiaoTrinh] CHECK CONSTRAINT [FK_GiaoTrinh_tblChiTietGiaoTrinh]
GO
ALTER TABLE [dbo].[tblGiaoTrinh]  WITH CHECK ADD  CONSTRAINT [FK_GiaoTrinh_tblMonHoc] FOREIGN KEY([FK_iMonHocID])
REFERENCES [dbo].[tblMonHoc] ([PK_iMonHocID])
GO
ALTER TABLE [dbo].[tblGiaoTrinh] CHECK CONSTRAINT [FK_GiaoTrinh_tblMonHoc]
GO
ALTER TABLE [dbo].[tblMonHoc]  WITH CHECK ADD  CONSTRAINT [CK_tblMonHoc_sTenMonHoc] CHECK  (([sTenMonHoc]<>''))
GO
ALTER TABLE [dbo].[tblMonHoc] CHECK CONSTRAINT [CK_tblMonHoc_sTenMonHoc]
GO
