USE [DoAn_LopHocAo]
GO
/****** Object:  StoredProcedure [dbo].[tblBaiViet_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblBaiViet_Delete]
		@PK_lMaBaiViet	bigint
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblBaiViet]
	Where
		[PK_lMaBaiViet] 	= @PK_lMaBaiViet
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblBaiViet_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblBaiViet_Insert]
			@FK_sMaGV	varchar(50)
			,@PK_lMaBaiViet	bigint
			,@sTieuDe	nvarchar(500)
			,@sLinkAnh	varchar(200)
			,@sTag	nvarchar(500)
			,@sNoiDung	nvarchar(max)
			,@iLuotXem	int
			,@sMoTa	nvarchar(200)
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblBaiViet]( [FK_sMaGV]
				,[sTieuDe]
				,[sLinkAnh]
				,[sTag]
				,[sNoiDung]
				,[iLuotXem]
				,[tNgayViet]
				,[sMoTa]
				,[iTrangThai]
				)
		
	Values	( @FK_sMaGV
				,@sTieuDe
				,@sLinkAnh
				,@sTag
				,@sNoiDung
				,@iLuotXem
				,GETDATE()
				,@sMoTa
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblBaiViet_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblBaiViet_Search]
			@FK_sMaGV	varchar(50)
			,@PK_lMaBaiViet	bigint
			,@sTieuDe	nvarchar(500)
			,@sLinkAnh	varchar(200)
			,@sTag	nvarchar(500)
			,@sNoiDung	nvarchar(max)
			,@iLuotXem	int
			,@tNgayViet	datetime
			,@tNgayCapNhat	datetime
			,@sMoTa	nvarchar(200)
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaGV]
				, [PK_lMaBaiViet]
				, [sTieuDe]
				, [sLinkAnh]
				, [sTag]
				, [sNoiDung]
				, [iLuotXem]
				, [tNgayViet]
				, [tNgayCapNhat]
				, [sMoTa]
				, [iTrangThai]
	From	[tblBaiViet]
	Where
		(@FK_sMaGV is null or [FK_sMaGV] 	like '%' + @FK_sMaGV+ '%')
		AND (@PK_lMaBaiViet is null or [PK_lMaBaiViet] 	like '%' + @PK_lMaBaiViet+ '%')
		AND (@sTieuDe is null or [sTieuDe] 	like '%' + @sTieuDe+ '%')
		AND (@sLinkAnh is null or [sLinkAnh] 	like '%' + @sLinkAnh+ '%')
		AND (@sTag is null or [sTag] 	like '%' + @sTag+ '%')
		AND (@sNoiDung is null or [sNoiDung] 	like '%' + @sNoiDung+ '%')
		AND (@iLuotXem is null or [iLuotXem] 	= @iLuotXem)
		AND (@tNgayViet is null or [tNgayViet] 	= @tNgayViet)
		AND (@tNgayCapNhat is null or [tNgayCapNhat] 	= @tNgayCapNhat)
		AND (@sMoTa is null or [sMoTa] 	like '%' + @sMoTa+ '%')
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblBaiViet_SelectByFK_sMaGV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	
CREATE PROCEDURE [dbo].[tblBaiViet_SelectByFK_sMaGV]
		@FK_sMaGV	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_sMaGV]
				, [PK_lMaBaiViet]
				, [sTieuDe]
				, [sLinkAnh]
				, [sTag]
				, [sNoiDung]
				, [iLuotXem]
				, [tNgayViet]
				, [tNgayCapNhat]
				, [sMoTa]
				, [iTrangThai]
	From	[tblBaiViet]
	Where	FK_sMaGV	= @FK_sMaGV
END


GO
/****** Object:  StoredProcedure [dbo].[tblBaiViet_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblBaiViet_SelectItem]
		@PK_lMaBaiViet	bigint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaGV]
				, [PK_lMaBaiViet]
				, [sTieuDe]
				, [sLinkAnh]
				, [sTag]
				, [sNoiDung]
				, [iLuotXem]
				, [tNgayViet]
				, [tNgayCapNhat]
				, [sMoTa]
				, [iTrangThai]
	From	[tblBaiViet]
	Where
		[PK_lMaBaiViet] 	= @PK_lMaBaiViet
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblBaiViet_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblBaiViet_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaGV]
				, [PK_lMaBaiViet]
				, [sTieuDe]
				, [sLinkAnh]
				, [sTag]
				, [sNoiDung]
				, [iLuotXem]
				, [tNgayViet]
				, [tNgayCapNhat]
				, [sMoTa]
				, [iTrangThai]
	From	[tblBaiViet]
	Order by [PK_lMaBaiViet]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblBaiViet_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblBaiViet_Update]
		@FK_sMaGV	varchar(50)
		,@PK_lMaBaiViet	bigint
		,@sTieuDe	nvarchar(500)
		,@sLinkAnh	varchar(200)
		,@sTag	nvarchar(500)
		,@sNoiDung	nvarchar(max)
		,@iLuotXem	int
		,@sMoTa	nvarchar(200)
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblBaiViet]	SET
		 [FK_sMaGV] 	= @FK_sMaGV
		,[sTieuDe] 	= @sTieuDe
		,[sLinkAnh] 	= @sLinkAnh
		,[sTag] 	= @sTag
		,[sNoiDung] 	= @sNoiDung
		,[iLuotXem] 	= @iLuotXem
		,[tNgayCapNhat] 	= GETDATE()
		,[sMoTa] 	= @sMoTa
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_lMaBaiViet] 	= @PK_lMaBaiViet
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblBaiViet_Update_iLuotXem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblBaiViet_Update_iLuotXem]
		@PK_lMaBaiViet	bigint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblBaiViet]	SET
		 [iLuotXem] 	= (SELECT [iLuotXem] FROM [tblBaiViet] WHERE PK_lMaBaiViet = @PK_lMaBaiViet) + 1
	WHERE 
		[PK_lMaBaiViet] 	= @PK_lMaBaiViet
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_Check_Question_Answer]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[tblCauHoi_Check_Question_Answer]
@PK_lCauhoi_ID BIGINT,
@iCauhoi_Dung SMALLINT
AS
BEGIN
DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM tblCauHoi WHERE (PK_lCauhoi_ID = @PK_lCauhoi_ID) AND (iCauhoi_Dung = @iCauhoi_Dung))
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value as return_value
END
GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_CountAll]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[tblCauHoi_CountAll]
AS
BEGIN
SELECT COUNT(*) AS [SumQuestion] FROM tblCauHoi
END
GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblCauHoi_Delete]
		@PK_lCauhoi_ID	bigint
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblCauHoi]
	Where
		[PK_lCauhoi_ID] 	= @PK_lCauhoi_ID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblCauHoi_Insert]
			@FK_sMaGV	varchar(50)
			,@PK_lCauhoi_ID	bigint
			,@sCauhoi_Cauhoi	nvarchar(500)
			,@sCauhoi_A	nvarchar(500)
			,@sCauhoi_B	nvarchar(500)
			,@sCauhoi_C	nvarchar(500)
			,@sCauhoi_D	nvarchar(500)
			,@iCauhoi_Dung	smallint
			,@sBoCauHoi	varchar(50)
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblCauHoi]( [FK_sMaGV]
				,[sCauhoi_Cauhoi]
				,[sCauhoi_A]
				,[sCauhoi_B]
				,[sCauhoi_C]
				,[sCauhoi_D]
				,[iCauhoi_Dung]
				,[sBoCauHoi]
				,[tNgayTao]
				,[iTrangThai]
				)
		
	Values	( @FK_sMaGV
				,@sCauhoi_Cauhoi
				,@sCauhoi_A
				,@sCauhoi_B
				,@sCauhoi_C
				,@sCauhoi_D
				,@iCauhoi_Dung
				,@sBoCauHoi
				,GETDATE()
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblCauHoi_Search]
			@FK_sMaGV	varchar(50)
			,@PK_lCauhoi_ID	bigint
			,@sCauhoi_Cauhoi	nvarchar(500)
			,@sCauhoi_A	nvarchar(500)
			,@sCauhoi_B	nvarchar(500)
			,@sCauhoi_C	nvarchar(500)
			,@sCauhoi_D	nvarchar(500)
			,@iCauhoi_Dung	smallint
			,@sBoCauHoi	varchar(50)
			,@tNgayTao	datetime
			,@tNgayCapNhat	datetime
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaGV]
				, [PK_lCauhoi_ID]
				, [sCauhoi_Cauhoi]
				, [sCauhoi_A]
				, [sCauhoi_B]
				, [sCauhoi_C]
				, [sCauhoi_D]
				, [iCauhoi_Dung]
				, [sBoCauHoi]
				, [tNgayTao]
				, [tNgayCapNhat]
				, [iTrangThai]
	From	[tblCauHoi]
	Where
		(@FK_sMaGV is null or [FK_sMaGV] 	like '%' + @FK_sMaGV+ '%')
		AND (@PK_lCauhoi_ID is null or [PK_lCauhoi_ID] 	like '%' + @PK_lCauhoi_ID+ '%')
		AND (@sCauhoi_Cauhoi is null or [sCauhoi_Cauhoi] 	like '%' + @sCauhoi_Cauhoi+ '%')
		AND (@sCauhoi_A is null or [sCauhoi_A] 	like '%' + @sCauhoi_A+ '%')
		AND (@sCauhoi_B is null or [sCauhoi_B] 	like '%' + @sCauhoi_B+ '%')
		AND (@sCauhoi_C is null or [sCauhoi_C] 	like '%' + @sCauhoi_C+ '%')
		AND (@sCauhoi_D is null or [sCauhoi_D] 	like '%' + @sCauhoi_D+ '%')
		AND (@iCauhoi_Dung is null or [iCauhoi_Dung] 	like '%' + @iCauhoi_Dung+ '%')
		AND (@sBoCauHoi is null or [sBoCauHoi] 	like '%' + @sBoCauHoi+ '%')
		AND (@tNgayTao is null or [tNgayTao] 	= @tNgayTao)
		AND (@tNgayCapNhat is null or [tNgayCapNhat] 	= @tNgayCapNhat)
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_SelectByFK_sMaGV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	
CREATE PROCEDURE [dbo].[tblCauHoi_SelectByFK_sMaGV]
		@FK_sMaGV	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_sMaGV]
				, [PK_lCauhoi_ID]
				, [sCauhoi_Cauhoi]
				, [sCauhoi_A]
				, [sCauhoi_B]
				, [sCauhoi_C]
				, [sCauhoi_D]
				, [iCauhoi_Dung]
				, [sBoCauHoi]
				, [tNgayTao]
				, [tNgayCapNhat]
				, [iTrangThai]
	From	[tblCauHoi]
	Where	FK_sMaGV	= @FK_sMaGV
END


GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblCauHoi_SelectItem]
		@PK_lCauhoi_ID	bigint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaGV]
				, [PK_lCauhoi_ID]
				, [sCauhoi_Cauhoi]
				, [sCauhoi_A]
				, [sCauhoi_B]
				, [sCauhoi_C]
				, [sCauhoi_D]
				, [iCauhoi_Dung]
				, [sBoCauHoi]
				, [tNgayTao]
				, [tNgayCapNhat]
				, [iTrangThai]
	From	[tblCauHoi]
	Where
		[PK_lCauhoi_ID] 	= @PK_lCauhoi_ID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblCauHoi_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaGV]
				, [PK_lCauhoi_ID]
				, [sCauhoi_Cauhoi]
				, [sCauhoi_A]
				, [sCauhoi_B]
				, [sCauhoi_C]
				, [sCauhoi_D]
				, [iCauhoi_Dung]
				, [sBoCauHoi]
				, [tNgayTao]
				, [tNgayCapNhat]
				, [iTrangThai]
	From	[tblCauHoi]
	Order by [PK_lCauhoi_ID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_SelectList_PK_lCauhoi_ID]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[tblCauHoi_SelectList_PK_lCauhoi_ID]
AS
BEGIN
SELECT PK_lCauhoi_ID FROM tblCauHoi
END
GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_SelectList_Question_by_Array_PK_lCauhoi_ID]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[tblCauHoi_SelectList_Question_by_Array_PK_lCauhoi_ID]
@ListPK_lCauhoi_ID VARCHAR(1000)
AS
BEGIN
SELECT * FROM tblCauHoi WHERE (PK_lCauhoi_ID IN (SELECT StringValue FROM StringCommASplit(@ListPK_lCauhoi_ID)))
END
GO
/****** Object:  StoredProcedure [dbo].[tblCauHoi_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblCauHoi_Update]
		@FK_sMaGV	varchar(50)
		,@PK_lCauhoi_ID	bigint
		,@sCauhoi_Cauhoi	nvarchar(500)
		,@sCauhoi_A	nvarchar(500)
		,@sCauhoi_B	nvarchar(500)
		,@sCauhoi_C	nvarchar(500)
		,@sCauhoi_D	nvarchar(500)
		,@iCauhoi_Dung	smallint
		,@sBoCauHoi	varchar(50)
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblCauHoi]	SET
		 [FK_sMaGV] 	= @FK_sMaGV
		,[sCauhoi_Cauhoi] 	= @sCauhoi_Cauhoi
		,[sCauhoi_A] 	= @sCauhoi_A
		,[sCauhoi_B] 	= @sCauhoi_B
		,[sCauhoi_C] 	= @sCauhoi_C
		,[sCauhoi_D] 	= @sCauhoi_D
		,[iCauhoi_Dung] 	= @iCauhoi_Dung
		,[sBoCauHoi] 	= @sBoCauHoi
		,[tNgayCapNhat] 	= GETDATE()
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_lCauhoi_ID] 	= @PK_lCauhoi_ID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblConfig_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblConfig_Delete]
		@PK_lConfigID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblConfig]
	Where
		[PK_lConfigID] 	= @PK_lConfigID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblConfig_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblConfig_Insert]
			@PK_lConfigID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblConfig]( [PK_lConfigID]
				)
		
	Values	( @PK_lConfigID
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblConfig_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblConfig_Search]
			@PK_lConfigID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_lConfigID]
	From	[tblConfig]
	Where
		(@PK_lConfigID is null or [PK_lConfigID] 	= @PK_lConfigID)
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblConfig_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblConfig_SelectItem]
		@PK_lConfigID	int
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_lConfigID]
	From	[tblConfig]
	Where
		[PK_lConfigID] 	= @PK_lConfigID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblConfig_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblConfig_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_lConfigID]
	From	[tblConfig]
	Order by [PK_lConfigID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblConfig_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblConfig_Update]
		@PK_lConfigID	int
AS
BEGIN
	SET NOCOUNT ON;
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDiemThi_CheckExists]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDiemThi_CheckExists]
		@FK_sMaSV	VARCHAR(50)
		,@FK_sMaMonhoc	VARCHAR(50)
		,@PK_iSolanhoc	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblDiemThi] WHERE [FK_sMaSV] = @FK_sMaSV AND [FK_sMaMonhoc] = @FK_sMaMonhoc AND [PK_iSolanhoc] = @PK_iSolanhoc)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value as return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblDiemThi_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDiemThi_Delete]
		@FK_sMaSV	varchar(50)
		,@FK_sMaMonhoc	varchar(50)
		,@PK_iSolanhoc	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblDiemThi]
	Where
		[FK_sMaSV] 	= @FK_sMaSV
		AND [FK_sMaMonhoc] 	= @FK_sMaMonhoc
		AND [PK_iSolanhoc] 	= @PK_iSolanhoc
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDiemThi_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDiemThi_Insert]
			@FK_sMaSV	varchar(50)
			,@FK_sMaMonhoc	varchar(50)
			,@PK_iSolanhoc	smallint
			,@fDiemchuyencan	float
			,@fDiemgiuaky	float
			,@fDiemthilan1	float
			,@fDiemthilan2	float
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblDiemThi]( [FK_sMaSV]
				,[FK_sMaMonhoc]
				,[PK_iSolanhoc]
				,[fDiemchuyencan]
				,[fDiemgiuaky]
				,[fDiemthilan1]
				,[fDiemthilan2]
				,[iTrangThai]
				)
		
	Values	( @FK_sMaSV
				,@FK_sMaMonhoc
				,@PK_iSolanhoc
				,@fDiemchuyencan
				,@fDiemgiuaky
				,@fDiemthilan1
				,@fDiemthilan2
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblDiemThi_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDiemThi_Search]
			@FK_sMaSV	varchar(50)
			,@FK_sMaMonhoc	varchar(50)
			,@PK_iSolanhoc	smallint
			,@fDiemchuyencan	float
			,@fDiemgiuaky	float
			,@fDiemthilan1	float
			,@fDiemthilan2	float
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaSV]
				, [FK_sMaMonhoc]
				, [PK_iSolanhoc]
				, [fDiemchuyencan]
				, [fDiemgiuaky]
				, [fDiemthilan1]
				, [fDiemthilan2]
				, [iTrangThai]
	From	[tblDiemThi]
	Where
		(@FK_sMaSV is null or [FK_sMaSV] 	like '%' + @FK_sMaSV+ '%')
		AND (@FK_sMaMonhoc is null or [FK_sMaMonhoc] 	like '%' + @FK_sMaMonhoc+ '%')
		AND (@PK_iSolanhoc is null or [PK_iSolanhoc] 	like '%' + @PK_iSolanhoc+ '%')
		AND (@fDiemchuyencan is null or [fDiemchuyencan] 	like '%' + @fDiemchuyencan+ '%')
		AND (@fDiemgiuaky is null or [fDiemgiuaky] 	like '%' + @fDiemgiuaky+ '%')
		AND (@fDiemthilan1 is null or [fDiemthilan1] 	like '%' + @fDiemthilan1+ '%')
		AND (@fDiemthilan2 is null or [fDiemthilan2] 	like '%' + @fDiemthilan2+ '%')
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDiemThi_SelectByFK_sMaMonhoc]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
	
CREATE PROCEDURE [dbo].[tblDiemThi_SelectByFK_sMaMonhoc]
		@FK_sMaMonhoc	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_sMaSV]
				, [FK_sMaMonhoc]
				, [PK_iSolanhoc]
				, [fDiemchuyencan]
				, [fDiemgiuaky]
				, [fDiemthilan1]
				, [fDiemthilan2]
				, [iTrangThai]
	From	[tblDiemThi]
	Where	FK_sMaMonhoc	= @FK_sMaMonhoc
END


GO
/****** Object:  StoredProcedure [dbo].[tblDiemThi_SelectByFK_sMaSV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	
CREATE PROCEDURE [dbo].[tblDiemThi_SelectByFK_sMaSV]
		@FK_sMaSV	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_sMaSV]
				, [FK_sMaMonhoc]
				, [PK_iSolanhoc]
				, [fDiemchuyencan]
				, [fDiemgiuaky]
				, [fDiemthilan1]
				, [fDiemthilan2]
				, [iTrangThai]
	From	[tblDiemThi]
	Where	FK_sMaSV	= @FK_sMaSV
END


GO
/****** Object:  StoredProcedure [dbo].[tblDiemThi_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDiemThi_SelectItem]
		@FK_sMaSV	varchar(50)
		,@FK_sMaMonhoc	varchar(50)
		,@PK_iSolanhoc	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaSV]
				, [FK_sMaMonhoc]
				, [PK_iSolanhoc]
				, [fDiemchuyencan]
				, [fDiemgiuaky]
				, [fDiemthilan1]
				, [fDiemthilan2]
				, [iTrangThai]
	From	[tblDiemThi]
	Where
		[FK_sMaSV] 	= @FK_sMaSV
		AND [FK_sMaMonhoc] 	= @FK_sMaMonhoc
		AND [PK_iSolanhoc] 	= @PK_iSolanhoc
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDiemThi_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDiemThi_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaSV]
				, [FK_sMaMonhoc]
				, [PK_iSolanhoc]
				, [fDiemchuyencan]
				, [fDiemgiuaky]
				, [fDiemthilan1]
				, [fDiemthilan2]
				, [iTrangThai]
	From	[tblDiemThi]
	Order by [FK_sMaSV], [FK_sMaMonhoc], [PK_iSolanhoc]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblDiemThi_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblDiemThi_Update]
		@FK_sMaSV	varchar(50)
		,@FK_sMaMonhoc	varchar(50)
		,@PK_iSolanhoc	smallint
		,@fDiemchuyencan	float
		,@fDiemgiuaky	float
		,@fDiemthilan1	float
		,@fDiemthilan2	float
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblDiemThi]	SET
		 [fDiemchuyencan] 	= @fDiemchuyencan
		,[fDiemgiuaky] 	= @fDiemgiuaky
		,[fDiemthilan1] 	= @fDiemthilan1
		,[fDiemthilan2] 	= @fDiemthilan2
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[FK_sMaSV] 	= @FK_sMaSV
		AND [FK_sMaMonhoc] 	= @FK_sMaMonhoc
		AND [PK_iSolanhoc] 	= @PK_iSolanhoc
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblError_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblError_Delete]
		@PK_lErrorID	bigint
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblError]
	Where
		[PK_lErrorID] 	= @PK_lErrorID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblError_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblError_Insert]
			@PK_lErrorID	bigint
			,@sLink	varchar(200)
			,@sIP	varchar(15)
			,@sBrowser	varchar(200)
			,@iCodes	smallint
			,@iStatus	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblError]([sLink]
				,[sIP]
				,[sBrowser]
				,[iCodes]
				,[tTime]
				,[iStatus]
				)
		
	Values	(@sLink
				,@sIP
				,@sBrowser
				,@iCodes
				,GETDATE()
				,@iStatus
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblError_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblError_Search]
			@PK_lErrorID	bigint
			,@sLink	varchar(200)
			,@sIP	varchar(15)
			,@sBrowser	varchar(200)
			,@iCodes	smallint
			,@tTime	datetime
			,@tTimeCheck	datetime
			,@iStatus	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_lErrorID]
				, [sLink]
				, [sIP]
				, [sBrowser]
				, [iCodes]
				, [tTime]
				, [tTimeCheck]
				, [iStatus]
	From	[tblError]
	Where
		(@PK_lErrorID is null or [PK_lErrorID] 	like '%' + @PK_lErrorID+ '%')
		AND (@sLink is null or [sLink] 	like '%' + @sLink+ '%')
		AND (@sIP is null or [sIP] 	like '%' + @sIP+ '%')
		AND (@sBrowser is null or [sBrowser] 	like '%' + @sBrowser+ '%')
		AND (@iCodes is null or [iCodes] 	like '%' + @iCodes+ '%')
		AND (@tTime is null or [tTime] 	= @tTime)
		AND (@tTimeCheck is null or [tTimeCheck] 	= @tTimeCheck)
		AND (@iStatus is null or [iStatus] 	like '%' + @iStatus+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblError_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblError_SelectItem]
		@PK_lErrorID	bigint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_lErrorID]
				, [sLink]
				, [sIP]
				, [sBrowser]
				, [iCodes]
				, [tTime]
				, [tTimeCheck]
				, [iStatus]
	From	[tblError]
	Where
		[PK_lErrorID] 	= @PK_lErrorID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblError_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblError_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_lErrorID]
				, [sLink]
				, [sIP]
				, [sBrowser]
				, [iCodes]
				, [tTime]
				, [tTimeCheck]
				, [iStatus]
	From	[tblError]
	Order by [PK_lErrorID]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblError_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblError_Update]
		@PK_lErrorID	bigint
		,@sLink	varchar(200)
		,@sIP	varchar(15)
		,@sBrowser	varchar(200)
		,@iCodes	smallint
		,@iStatus	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblError]	SET
		 [sLink] 	= @sLink
		,[sIP] 	= @sIP
		,[sBrowser] 	= @sBrowser
		,[iCodes] 	= @iCodes
		,[tTimeCheck] 	= GETDATE()
		,[iStatus] 	= @iStatus
	WHERE 
		[PK_lErrorID] 	= @PK_lErrorID
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_CheckExists_PK_sMaGV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_CheckExists_PK_sMaGV]
		@PK_sMaGV	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblGiangVien] WHERE [PK_sMaGV] = @PK_sMaGV)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_CheckExists_sCMNDGV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_CheckExists_sCMNDGV]
		@sCMNDGV	VARCHAR(9)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblGiangVien] WHERE [sCMNDGV] = @sCMNDGV)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value
END
GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_CheckExists_sEmailGV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_CheckExists_sEmailGV]
		@sEmailGV	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblGiangVien] WHERE [sEmailGV] = @sEmailGV)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_CheckExists_sTendangnhapGV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_CheckExists_sTendangnhapGV]
		@sTendangnhapGV	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblGiangVien] WHERE [sTendangnhapGV] = @sTendangnhapGV)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	28/03/2014 21:32
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_Delete]
		@PK_sMaGV	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblGiangVien]
	Where
		[PK_sMaGV] 	= @PK_sMaGV
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:32
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_Insert]
			@PK_sMaGV	varchar(50)
			,@sHoTenGV	nvarchar(100)
			,@sTendangnhapGV	varchar(50)
			,@sMatkhauGV	varchar(50)
			,@sEmailGV	varchar(50)
			,@sDiachiGV	nvarchar(100)
			,@sSdtGV	varchar(13)
			,@tNgaysinhGV	datetime
			,@bGioitinhGV	bit
			,@sCMNDGV	varchar(9)
			,@tNgayCapCMNDGV	datetime
			,@sNoiCapCMNDGV	nvarchar(100)
			,@bHonNhanGV	bit
			,@tNgayNhanCongTacGV	datetime
			,@iChucVuGV	smallint
			,@iHocViGV	smallint
			,@bCongChucGV	bit
			,@sLinkChannelsGV	varchar(200)
			,@sLinkChatRoomsGV	varchar(200)
			,@sLinkAvatarGV	varchar(200)
			,@iTrangThaiGV	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblGiangVien]( [PK_sMaGV]
				,[sHoTenGV]
				,[sTendangnhapGV]
				,[sMatkhauGV]
				,[sEmailGV]
				,[sDiachiGV]
				,[sSdtGV]
				,[tNgaysinhGV]
				,[bGioitinhGV]
				,[sCMNDGV]
				,[tNgayCapCMNDGV]
				,[sNoiCapCMNDGV]
				,[bHonNhanGV]
				,[tNgayNhanCongTacGV]
				,[iChucVuGV]
				,[iHocViGV]
				,[bCongChucGV]
				,[sLinkChannelsGV]
				,[sLinkChatRoomsGV]
				,[sLinkAvatarGV]
				,[iTrangThaiGV]
				)
		
	Values	( @PK_sMaGV
				,@sHoTenGV
				,@sTendangnhapGV
				,@sMatkhauGV
				,@sEmailGV
				,@sDiachiGV
				,@sSdtGV
				,@tNgaysinhGV
				,@bGioitinhGV
				,@sCMNDGV
				,@tNgayCapCMNDGV
				,@sNoiCapCMNDGV
				,@bHonNhanGV
				,@tNgayNhanCongTacGV
				,@iChucVuGV
				,@iHocViGV
				,@bCongChucGV
				,@sLinkChannelsGV
				,@sLinkChatRoomsGV
				,@sLinkAvatarGV
				,@iTrangThaiGV
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_Login]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_Login]
			@sTendangnhapGV	varchar(50)
			,@sMatkhauGV	varchar(50)
			,@iTrangThaiGV	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaGV]
				, [sHoTenGV]
				, [sTendangnhapGV]
				, [sMatkhauGV]
				, [sEmailGV]
				, [sDiachiGV]
				, [sSdtGV]
				, [tNgaysinhGV]
				, [bGioitinhGV]
				, [sCMNDGV]
				, [tNgayCapCMNDGV]
				, [sNoiCapCMNDGV]
				, [bHonNhanGV]
				, [tNgayNhanCongTacGV]
				, [iChucVuGV]
				, [iHocViGV]
				, [bCongChucGV]
				, [sLinkChannelsGV]
				, [sLinkChatRoomsGV]
				, [sLinkAvatarGV]
				, [iTrangThaiGV]
	From	[tblGiangVien]
	Where
		([sTendangnhapGV] 	like  @sTendangnhapGV)
		AND ([sMatkhauGV] 	like @sMatkhauGV)
		AND ([iTrangThaiGV] 	= @iTrangThaiGV)
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:32
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_Search]
			@PK_sMaGV	varchar(50)
			,@sHoTenGV	nvarchar(100)
			,@sTendangnhapGV	varchar(50)
			,@sMatkhauGV	varchar(50)
			,@sEmailGV	varchar(50)
			,@sDiachiGV	nvarchar(100)
			,@sSdtGV	varchar(13)
			,@tNgaysinhGV	datetime
			,@bGioitinhGV	bit
			,@sCMNDGV	varchar(9)
			,@tNgayCapCMNDGV	datetime
			,@sNoiCapCMNDGV	nvarchar(100)
			,@bHonNhanGV	bit
			,@tNgayNhanCongTacGV	datetime
			,@iChucVuGV	smallint
			,@iHocViGV	smallint
			,@bCongChucGV	bit
			,@sLinkChannelsGV	varchar(200)
			,@sLinkChatRoomsGV	varchar(200)
			,@sLinkAvatarGV	varchar(200)
			,@iTrangThaiGV	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaGV]
				, [sHoTenGV]
				, [sTendangnhapGV]
				, [sMatkhauGV]
				, [sEmailGV]
				, [sDiachiGV]
				, [sSdtGV]
				, [tNgaysinhGV]
				, [bGioitinhGV]
				, [sCMNDGV]
				, [tNgayCapCMNDGV]
				, [sNoiCapCMNDGV]
				, [bHonNhanGV]
				, [tNgayNhanCongTacGV]
				, [iChucVuGV]
				, [iHocViGV]
				, [bCongChucGV]
				, [sLinkChannelsGV]
				, [sLinkChatRoomsGV]
				, [sLinkAvatarGV]
				, [iTrangThaiGV]
	From	[tblGiangVien]
	Where
		(@PK_sMaGV is null or [PK_sMaGV] 	like '%' + @PK_sMaGV+ '%')
		AND (@sHoTenGV is null or [sHoTenGV] 	like '%' + @sHoTenGV+ '%')
		AND (@sTendangnhapGV is null or [sTendangnhapGV] 	like '%' + @sTendangnhapGV+ '%')
		AND (@sMatkhauGV is null or [sMatkhauGV] 	like '%' + @sMatkhauGV+ '%')
		AND (@sEmailGV is null or [sEmailGV] 	like '%' + @sEmailGV+ '%')
		AND (@sDiachiGV is null or [sDiachiGV] 	like '%' + @sDiachiGV+ '%')
		AND (@sSdtGV is null or [sSdtGV] 	like '%' + @sSdtGV+ '%')
		AND (@tNgaysinhGV is null or [tNgaysinhGV] 	= @tNgaysinhGV)
		AND (@bGioitinhGV is null or [bGioitinhGV] 	= @bGioitinhGV)
		AND (@sCMNDGV is null or [sCMNDGV] 	like '%' + @sCMNDGV+ '%')
		AND (@tNgayCapCMNDGV is null or [tNgayCapCMNDGV] 	= @tNgayCapCMNDGV)
		AND (@sNoiCapCMNDGV is null or [sNoiCapCMNDGV] 	like '%' + @sNoiCapCMNDGV+ '%')
		AND (@bHonNhanGV is null or [bHonNhanGV] 	= @bHonNhanGV)
		AND (@tNgayNhanCongTacGV is null or [tNgayNhanCongTacGV] 	= @tNgayNhanCongTacGV)
		AND (@iChucVuGV is null or [iChucVuGV] 	like '%' + @iChucVuGV+ '%')
		AND (@iHocViGV is null or [iHocViGV] 	like '%' + @iHocViGV+ '%')
		AND (@bCongChucGV is null or [bCongChucGV] 	= @bCongChucGV)
		AND (@sLinkChannelsGV is null or [sLinkChannelsGV] 	like '%' + @sLinkChannelsGV+ '%')
		AND (@sLinkChatRoomsGV is null or [sLinkChatRoomsGV] 	like '%' + @sLinkChatRoomsGV+ '%')
		AND (@sLinkAvatarGV is null or [sLinkAvatarGV] 	like '%' + @sLinkAvatarGV+ '%')
		AND (@iTrangThaiGV is null or [iTrangThaiGV] 	like '%' + @iTrangThaiGV+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_SelectBysTendangnhapGV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:32
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_SelectBysTendangnhapGV]
		@sTendangnhapGV	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaGV]
				, [sHoTenGV]
				, [sTendangnhapGV]
				, [sMatkhauGV]
				, [sEmailGV]
				, [sDiachiGV]
				, [sSdtGV]
				, [tNgaysinhGV]
				, [bGioitinhGV]
				, [sCMNDGV]
				, [tNgayCapCMNDGV]
				, [sNoiCapCMNDGV]
				, [bHonNhanGV]
				, [tNgayNhanCongTacGV]
				, [iChucVuGV]
				, [iHocViGV]
				, [bCongChucGV]
				, [sLinkChannelsGV]
				, [sLinkChatRoomsGV]
				, [sLinkAvatarGV]
				, [iTrangThaiGV]
	From	[tblGiangVien]
	Where
		[sTendangnhapGV] 	= @sTendangnhapGV
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:32
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_SelectItem]
		@PK_sMaGV	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaGV]
				, [sHoTenGV]
				, [sTendangnhapGV]
				, [sMatkhauGV]
				, [sEmailGV]
				, [sDiachiGV]
				, [sSdtGV]
				, [tNgaysinhGV]
				, [bGioitinhGV]
				, [sCMNDGV]
				, [tNgayCapCMNDGV]
				, [sNoiCapCMNDGV]
				, [bHonNhanGV]
				, [tNgayNhanCongTacGV]
				, [iChucVuGV]
				, [iHocViGV]
				, [bCongChucGV]
				, [sLinkChannelsGV]
				, [sLinkChatRoomsGV]
				, [sLinkAvatarGV]
				, [iTrangThaiGV]
	From	[tblGiangVien]
	Where
		[PK_sMaGV] 	= @PK_sMaGV
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:32
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaGV]
				, [sHoTenGV]
				, [sTendangnhapGV]
				, [sMatkhauGV]
				, [sEmailGV]
				, [sDiachiGV]
				, [sSdtGV]
				, [tNgaysinhGV]
				, [bGioitinhGV]
				, [sCMNDGV]
				, [tNgayCapCMNDGV]
				, [sNoiCapCMNDGV]
				, [bHonNhanGV]
				, [tNgayNhanCongTacGV]
				, [iChucVuGV]
				, [iHocViGV]
				, [bCongChucGV]
				, [sLinkChannelsGV]
				, [sLinkChatRoomsGV]
				, [sLinkAvatarGV]
				, [iTrangThaiGV]
	From	[tblGiangVien]
	Order by [PK_sMaGV]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblGiangVien_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:32
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblGiangVien_Update]
		@PK_sMaGV	varchar(50)
		,@sHoTenGV	nvarchar(100)
		,@sTendangnhapGV	varchar(50)
		,@sMatkhauGV	varchar(50)
		,@sEmailGV	varchar(50)
		,@sDiachiGV	nvarchar(100)
		,@sSdtGV	varchar(13)
		,@tNgaysinhGV	datetime
		,@bGioitinhGV	bit
		,@sCMNDGV	varchar(9)
		,@tNgayCapCMNDGV	datetime
		,@sNoiCapCMNDGV	nvarchar(100)
		,@bHonNhanGV	bit
		,@tNgayNhanCongTacGV	datetime
		,@iChucVuGV	smallint
		,@iHocViGV	smallint
		,@bCongChucGV	bit
		,@sLinkChannelsGV	varchar(200)
		,@sLinkChatRoomsGV	varchar(200)
		,@sLinkAvatarGV	varchar(200)
		,@iTrangThaiGV	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblGiangVien]	SET
		 [sHoTenGV] 	= @sHoTenGV
		,[sTendangnhapGV] 	= @sTendangnhapGV
		,[sMatkhauGV] 	= @sMatkhauGV
		,[sEmailGV] 	= @sEmailGV
		,[sDiachiGV] 	= @sDiachiGV
		,[sSdtGV] 	= @sSdtGV
		,[tNgaysinhGV] 	= @tNgaysinhGV
		,[bGioitinhGV] 	= @bGioitinhGV
		,[sCMNDGV] 	= @sCMNDGV
		,[tNgayCapCMNDGV] 	= @tNgayCapCMNDGV
		,[sNoiCapCMNDGV] 	= @sNoiCapCMNDGV
		,[bHonNhanGV] 	= @bHonNhanGV
		,[tNgayNhanCongTacGV] 	= @tNgayNhanCongTacGV
		,[iChucVuGV] 	= @iChucVuGV
		,[iHocViGV] 	= @iHocViGV
		,[bCongChucGV] 	= @bCongChucGV
		,[sLinkChannelsGV] 	= @sLinkChannelsGV
		,[sLinkChatRoomsGV] 	= @sLinkChatRoomsGV
		,[sLinkAvatarGV] 	= @sLinkAvatarGV
		,[iTrangThaiGV] 	= @iTrangThaiGV
	WHERE 
		[PK_sMaGV] 	= @PK_sMaGV
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLichDayVaHoc_CheckExists]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLichDayVaHoc_CheckExists]
		@FK_sMaPCCT	VARCHAR(50)
		,@FK_sMalop	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblLichDayVaHoc] WHERE [FK_sMaPCCT] = @FK_sMaPCCT AND [FK_sMalop] = @FK_sMalop)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblLichDayVaHoc_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	23/03/2014 23:11
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLichDayVaHoc_Delete]
		@FK_sMaPCCT	varchar(50)
		,@FK_sMalop	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblLichDayVaHoc]
	Where
		[FK_sMaPCCT] 	= @FK_sMaPCCT
		AND [FK_sMalop] 	= @FK_sMalop
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLichDayVaHoc_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	23/03/2014 23:11
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLichDayVaHoc_Insert]
			@FK_sMaPCCT	varchar(50)
			,@FK_sMalop	varchar(50)
			,@iCaHoc	smallint
			,@tNgayDay	datetime
			,@iSoTietDay	smallint
			,@sSinhVienNghi	varchar(max)
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblLichDayVaHoc]( [FK_sMaPCCT]
				,[FK_sMalop]
				,[iCaHoc]
				,[tNgayDay]
				,[iSoTietDay]
				,[sSinhVienNghi]
				,[iTrangThai]
				)
		
	Values	( @FK_sMaPCCT
				,@FK_sMalop
				,@iCaHoc
				,@tNgayDay
				,@iSoTietDay
				,@sSinhVienNghi
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblLichDayVaHoc_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	23/03/2014 23:11
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLichDayVaHoc_Search]
			@FK_sMaPCCT	varchar(50)
			,@FK_sMalop	varchar(50)
			,@iCaHoc	smallint
			,@tNgayDay	datetime
			,@iSoTietDay	smallint
			,@sSinhVienNghi	varchar(max)
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaPCCT]
				, [FK_sMalop]
				, [iCaHoc]
				, [tNgayDay]
				, [iSoTietDay]
				, [sSinhVienNghi]
				, [iTrangThai]
	From	[tblLichDayVaHoc]
	Where
		(@FK_sMaPCCT is null or [FK_sMaPCCT] 	like '%' + @FK_sMaPCCT+ '%')
		AND (@FK_sMalop is null or [FK_sMalop] 	like '%' + @FK_sMalop+ '%')
		AND (@iCaHoc is null or [iCaHoc] 	like '%' + @iCaHoc+ '%')
		AND (@tNgayDay is null or [tNgayDay] 	= @tNgayDay)
		AND (@iSoTietDay is null or [iSoTietDay] 	like '%' + @iSoTietDay+ '%')
		AND (@sSinhVienNghi is null or [sSinhVienNghi] 	like '%' + @sSinhVienNghi+ '%')
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLichDayVaHoc_SelectByFK_sMalop]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
	
CREATE PROCEDURE [dbo].[tblLichDayVaHoc_SelectByFK_sMalop]
		@FK_sMalop	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_sMaPCCT]
				, [FK_sMalop]
				, [iCaHoc]
				, [tNgayDay]
				, [iSoTietDay]
				, [sSinhVienNghi]
				, [iTrangThai]
	From	[tblLichDayVaHoc]
	Where	FK_sMalop	= @FK_sMalop
END


GO
/****** Object:  StoredProcedure [dbo].[tblLichDayVaHoc_SelectByFK_sMaPCCT]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	
CREATE PROCEDURE [dbo].[tblLichDayVaHoc_SelectByFK_sMaPCCT]
		@FK_sMaPCCT	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_sMaPCCT]
				, [FK_sMalop]
				, [iCaHoc]
				, [tNgayDay]
				, [iSoTietDay]
				, [sSinhVienNghi]
				, [iTrangThai]
	From	[tblLichDayVaHoc]
	Where	FK_sMaPCCT	= @FK_sMaPCCT
END


GO
/****** Object:  StoredProcedure [dbo].[tblLichDayVaHoc_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	23/03/2014 23:11
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLichDayVaHoc_SelectItem]
		@FK_sMaPCCT	varchar(50)
		,@FK_sMalop	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaPCCT]
				, [FK_sMalop]
				, [iCaHoc]
				, [tNgayDay]
				, [iSoTietDay]
				, [sSinhVienNghi]
				, [iTrangThai]
	From	[tblLichDayVaHoc]
	Where
		[FK_sMaPCCT] 	= @FK_sMaPCCT
		AND [FK_sMalop] 	= @FK_sMalop
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLichDayVaHoc_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	23/03/2014 23:11
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLichDayVaHoc_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaPCCT]
				, [FK_sMalop]
				, [iCaHoc]
				, [tNgayDay]
				, [iSoTietDay]
				, [sSinhVienNghi]
				, [iTrangThai]
	From	[tblLichDayVaHoc]
	Order by [FK_sMaPCCT], [FK_sMalop]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLichDayVaHoc_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	23/03/2014 23:11
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLichDayVaHoc_Update]
		@FK_sMaPCCT	varchar(50)
		,@FK_sMalop	varchar(50)
		,@iCaHoc	smallint
		,@tNgayDay	datetime
		,@iSoTietDay	smallint
		,@sSinhVienNghi	varchar(max)
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblLichDayVaHoc]	SET
		 [iCaHoc] 	= @iCaHoc
		,[tNgayDay] 	= @tNgayDay
		,[iSoTietDay] 	= @iSoTietDay
		,[sSinhVienNghi] 	= @sSinhVienNghi
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[FK_sMaPCCT] 	= @FK_sMaPCCT
		AND [FK_sMalop] 	= @FK_sMalop
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLopHoc_CheckExists_PK_sMalop]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLopHoc_CheckExists_PK_sMalop]
		@PK_sMalop	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblLopHoc] WHERE [PK_sMalop] = @PK_sMalop)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblLopHoc_CheckExists_sTenlop]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLopHoc_CheckExists_sTenlop]
		@sTenlop	NVARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblLopHoc] WHERE [sTenlop] = @sTenlop)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblLopHoc_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLopHoc_Delete]
		@PK_sMalop	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblLopHoc]
	Where
		[PK_sMalop] 	= @PK_sMalop
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLopHoc_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLopHoc_Insert]
			@PK_sMalop	varchar(50)
			,@sTenlop	nvarchar(100)
			,@iNamvaotruong	smallint
			,@iSiso	smallint
			,@iSoNamDaoTao	smallint
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblLopHoc]( [PK_sMalop]
				,[sTenlop]
				,[iNamvaotruong]
				,[iSiso]
				,[iSoNamDaoTao]
				,[iTrangThai]
				)
		
	Values	( @PK_sMalop
				,@sTenlop
				,@iNamvaotruong
				,@iSiso
				,@iSoNamDaoTao
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblLopHoc_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLopHoc_Search]
			@PK_sMalop	varchar(50)
			,@sTenlop	nvarchar(100)
			,@iNamvaotruong	smallint
			,@iSiso	smallint
			,@iSoNamDaoTao	smallint
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMalop]
				, [sTenlop]
				, [iNamvaotruong]
				, [iSiso]
				, [iSoNamDaoTao]
				, [iTrangThai]
	From	[tblLopHoc]
	Where
		(@PK_sMalop is null or [PK_sMalop] 	like '%' + @PK_sMalop+ '%')
		AND (@sTenlop is null or [sTenlop] 	like '%' + @sTenlop+ '%')
		AND (@iNamvaotruong is null or [iNamvaotruong] 	like '%' + @iNamvaotruong+ '%')
		AND (@iSiso is null or [iSiso] 	like '%' + @iSiso+ '%')
		AND (@iSoNamDaoTao is null or [iSoNamDaoTao] 	like '%' + @iSoNamDaoTao+ '%')
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLopHoc_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLopHoc_SelectItem]
		@PK_sMalop	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMalop]
				, [sTenlop]
				, [iNamvaotruong]
				, [iSiso]
				, [iSoNamDaoTao]
				, [iTrangThai]
	From	[tblLopHoc]
	Where
		[PK_sMalop] 	= @PK_sMalop
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLopHoc_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLopHoc_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMalop]
				, [sTenlop]
				, [iNamvaotruong]
				, [iSiso]
				, [iSoNamDaoTao]
				, [iTrangThai]
	From	[tblLopHoc]
	Order by [PK_sMalop]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblLopHoc_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblLopHoc_Update]
		@PK_sMalop	varchar(50)
		,@sTenlop	nvarchar(100)
		,@iNamvaotruong	smallint
		,@iSiso	smallint
		,@iSoNamDaoTao	smallint
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblLopHoc]	SET
		 [sTenlop] 	= @sTenlop
		,[iNamvaotruong] 	= @iNamvaotruong
		,[iSiso] 	= @iSiso
		,[iSoNamDaoTao] 	= @iSoNamDaoTao
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_sMalop] 	= @PK_sMalop
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_CheckExists_PK_sMaMonhoc]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_CheckExists_PK_sMaMonhoc]
		@PK_sMaMonhoc	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblMonHoc] WHERE [PK_sMaMonhoc] = @PK_sMaMonhoc)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_CheckExists_sTenMonhoc]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_CheckExists_sTenMonhoc]
		@sTenMonhoc	NVARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblMonHoc] WHERE [sTenMonhoc] = @sTenMonhoc)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_Delete]
		@PK_sMaMonhoc	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblMonHoc]
	Where
		[PK_sMaMonhoc] 	= @PK_sMaMonhoc
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_Insert]
			@PK_sMaMonhoc	varchar(50)
			,@sTenMonhoc	nvarchar(100)
			,@iSotrinh	smallint
			,@iSotietday	smallint
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblMonHoc]( [PK_sMaMonhoc]
				,[sTenMonhoc]
				,[iSotrinh]
				,[iSotietday]
				,[iTrangThai]
				)
		
	Values	( @PK_sMaMonhoc
				,@sTenMonhoc
				,@iSotrinh
				,@iSotietday
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_Search]
			@PK_sMaMonhoc	varchar(50)
			,@sTenMonhoc	nvarchar(100)
			,@iSotrinh	smallint
			,@iSotietday	smallint
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaMonhoc]
				, [sTenMonhoc]
				, [iSotrinh]
				, [iSotietday]
				, [iTrangThai]
	From	[tblMonHoc]
	Where
		(@PK_sMaMonhoc is null or [PK_sMaMonhoc] 	like '%' + @PK_sMaMonhoc+ '%')
		AND (@sTenMonhoc is null or [sTenMonhoc] 	like '%' + @sTenMonhoc+ '%')
		AND (@iSotrinh is null or [iSotrinh] 	like '%' + @iSotrinh+ '%')
		AND (@iSotietday is null or [iSotietday] 	like '%' + @iSotietday+ '%')
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_SelectItem]
		@PK_sMaMonhoc	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaMonhoc]
				, [sTenMonhoc]
				, [iSotrinh]
				, [iSotietday]
				, [iTrangThai]
	From	[tblMonHoc]
	Where
		[PK_sMaMonhoc] 	= @PK_sMaMonhoc
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaMonhoc]
				, [sTenMonhoc]
				, [iSotrinh]
				, [iSotietday]
				, [iTrangThai]
	From	[tblMonHoc]
	Order by [PK_sMaMonhoc]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblMonHoc_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblMonHoc_Update]
		@PK_sMaMonhoc	varchar(50)
		,@sTenMonhoc	nvarchar(100)
		,@iSotrinh	smallint
		,@iSotietday	smallint
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblMonHoc]	SET
		 [sTenMonhoc] 	= @sTenMonhoc
		,[iSotrinh] 	= @iSotrinh
		,[iSotietday] 	= @iSotietday
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_sMaMonhoc] 	= @PK_sMaMonhoc
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblPhanCongCongTac_CheckExists]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblPhanCongCongTac_CheckExists]
		@PK_sMaPCCT	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblPhanCongCongTac] WHERE [PK_sMaPCCT] = @PK_sMaPCCT)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblPhanCongCongTac_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblPhanCongCongTac_Delete]
		@PK_sMaPCCT	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblPhanCongCongTac]
	Where
		[PK_sMaPCCT] 	= @PK_sMaPCCT
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblPhanCongCongTac_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblPhanCongCongTac_Insert]
			@PK_sMaPCCT	varchar(50)
			,@FK_sMaGV	varchar(50)
			,@FK_sMaMonhoc	varchar(50)
			,@tNgayBatDau	datetime
			,@tNgayKetThuc	datetime
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblPhanCongCongTac]( [PK_sMaPCCT]
				,[FK_sMaGV]
				,[FK_sMaMonhoc]
				,[tNgayBatDau]
				,[tNgayKetThuc]
				,[iTrangThai]
				)
		
	Values	( @PK_sMaPCCT
				,@FK_sMaGV
				,@FK_sMaMonhoc
				,@tNgayBatDau
				,@tNgayKetThuc
				,@iTrangThai
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblPhanCongCongTac_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblPhanCongCongTac_Search]
			@PK_sMaPCCT	varchar(50)
			,@FK_sMaGV	varchar(50)
			,@FK_sMaMonhoc	varchar(50)
			,@tNgayBatDau	datetime
			,@tNgayKetThuc	datetime
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaPCCT]
				, [FK_sMaGV]
				, [FK_sMaMonhoc]
				, [tNgayBatDau]
				, [tNgayKetThuc]
				, [iTrangThai]
	From	[tblPhanCongCongTac]
	Where
		(@PK_sMaPCCT is null or [PK_sMaPCCT] 	like '%' + @PK_sMaPCCT+ '%')
		AND (@FK_sMaGV is null or [FK_sMaGV] 	like '%' + @FK_sMaGV+ '%')
		AND (@FK_sMaMonhoc is null or [FK_sMaMonhoc] 	like '%' + @FK_sMaMonhoc+ '%')
		AND (@tNgayBatDau is null or [tNgayBatDau] 	= @tNgayBatDau)
		AND (@tNgayKetThuc is null or [tNgayKetThuc] 	= @tNgayKetThuc)
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblPhanCongCongTac_SelectByFK_sMaGV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	
CREATE PROCEDURE [dbo].[tblPhanCongCongTac_SelectByFK_sMaGV]
		@FK_sMaGV	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[PK_sMaPCCT]
				, [FK_sMaGV]
				, [FK_sMaMonhoc]
				, [tNgayBatDau]
				, [tNgayKetThuc]
				, [iTrangThai]
	From	[tblPhanCongCongTac]
	Where	FK_sMaGV	= @FK_sMaGV
END


GO
/****** Object:  StoredProcedure [dbo].[tblPhanCongCongTac_SelectByFK_sMaMonhoc]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
	
CREATE PROCEDURE [dbo].[tblPhanCongCongTac_SelectByFK_sMaMonhoc]
		@FK_sMaMonhoc	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[PK_sMaPCCT]
				, [FK_sMaGV]
				, [FK_sMaMonhoc]
				, [tNgayBatDau]
				, [tNgayKetThuc]
				, [iTrangThai]
	From	[tblPhanCongCongTac]
	Where	FK_sMaMonhoc	= @FK_sMaMonhoc
END


GO
/****** Object:  StoredProcedure [dbo].[tblPhanCongCongTac_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblPhanCongCongTac_SelectItem]
		@PK_sMaPCCT	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaPCCT]
				, [FK_sMaGV]
				, [FK_sMaMonhoc]
				, [tNgayBatDau]
				, [tNgayKetThuc]
				, [iTrangThai]
	From	[tblPhanCongCongTac]
	Where
		[PK_sMaPCCT] 	= @PK_sMaPCCT
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblPhanCongCongTac_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblPhanCongCongTac_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaPCCT]
				, [FK_sMaGV]
				, [FK_sMaMonhoc]
				, [tNgayBatDau]
				, [tNgayKetThuc]
				, [iTrangThai]
	From	[tblPhanCongCongTac]
	Order by [PK_sMaPCCT]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblPhanCongCongTac_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblPhanCongCongTac_Update]
		@PK_sMaPCCT	varchar(50)
		,@FK_sMaGV	varchar(50)
		,@FK_sMaMonhoc	varchar(50)
		,@tNgayBatDau	datetime
		,@tNgayKetThuc	datetime
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblPhanCongCongTac]	SET
		 [FK_sMaGV] 	= @FK_sMaGV
		,[FK_sMaMonhoc] 	= @FK_sMaMonhoc
		,[tNgayBatDau] = @tNgayBatDau
		,[tNgayKetThuc] 	= @tNgayKetThuc
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_sMaPCCT] 	= @PK_sMaPCCT
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_CheckExists_PK_sMaSV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_CheckExists_PK_sMaSV]
		@PK_sMaSV	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblSinhVien] WHERE [PK_sMaSV] = @PK_sMaSV)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_CheckExists_sCMNDSV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_CheckExists_sCMNDSV]
		@sCMNDSV	VARCHAR(9)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblSinhVien] WHERE [sCMNDSV] = @sCMNDSV)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_CheckExists_sEmailSV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_CheckExists_sEmailSV]
		@sEmailSV	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblSinhVien] WHERE [sEmailSV] = @sEmailSV)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_CheckExists_sTendangnhapSV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_CheckExists_sTendangnhapSV]
		@sTendangnhapSV	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE	@return_value BIT
	IF EXISTS(SELECT * FROM [tblSinhVien] WHERE [sTendangnhapSV] = @sTendangnhapSV)
		SET @return_value = 'TRUE'
	ELSE
		SET @return_value = 'FALSE'
    SELECT @return_value AS return_value		
END
GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_Delete]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_Delete]
		@PK_sMaSV	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblSinhVien]
	Where
		[PK_sMaSV] 	= @PK_sMaSV
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_Insert]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_Insert]
			@FK_sMaLop	varchar(50)
			,@PK_sMaSV	varchar(50)
			,@sHotenSV	nvarchar(100)
			,@sTendangnhapSV	varchar(50)
			,@sMatkhauSV	varchar(50)
			,@sEmailSV	varchar(50)
			,@sDiachiSV	nvarchar(100)
			,@sSdtSV	varchar(13)
			,@tNgaysinhSV	datetime
			,@bGioitinhSV	bit
			,@sCMNDSV	varchar(9)
			,@tNgayCapCMNDSV	datetime
			,@sNoiCapCMNDSV	nvarchar(100)
			,@bHonNhanSV	bit
			,@sNguoiLienHeSV	nvarchar(100)
			,@sDiaChiNguoiLienHeSV	nvarchar(100)
			,@sSdtNguoiLienHeSV	varchar(13)
			,@iQuanHeVoiNguoiLienHeSV	smallint
			,@bKetnapDoanSV	bit
			,@iNamketnapDoanSV	smallint
			,@sNoiketnapDoanSV	nvarchar(100)
			,@iNamtotnghiepTHPTSV	smallint
			,@tNgayNhapHocSV	datetime
			,@tNgayRaTruongSV	datetime
			,@tNgayCapTheSV	datetime
			,@sLinkAvatarSV	varchar(200)
			,@iTrangThaiSV	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblSinhVien]( [FK_sMaLop]
				,[PK_sMaSV]
				,[sHotenSV]
				,[sTendangnhapSV]
				,[sMatkhauSV]
				,[sEmailSV]
				,[sDiachiSV]
				,[sSdtSV]
				,[tNgaysinhSV]
				,[bGioitinhSV]
				,[sCMNDSV]
				,[tNgayCapCMNDSV]
				,[sNoiCapCMNDSV]
				,[bHonNhanSV]
				,[sNguoiLienHeSV]
				,[sDiaChiNguoiLienHeSV]
				,[sSdtNguoiLienHeSV]
				,[iQuanHeVoiNguoiLienHeSV]
				,[bKetnapDoanSV]
				,[iNamketnapDoanSV]
				,[sNoiketnapDoanSV]
				,[iNamtotnghiepTHPTSV]
				,[tNgayNhapHocSV]
				,[tNgayRaTruongSV]
				,[tNgayCapTheSV]
				,[sLinkAvatarSV]
				,[iTrangThaiSV]
				)
		
	Values	( @FK_sMaLop
				,@PK_sMaSV
				,@sHotenSV
				,@sTendangnhapSV
				,@sMatkhauSV
				,@sEmailSV
				,@sDiachiSV
				,@sSdtSV
				,@tNgaysinhSV
				,@bGioitinhSV
				,@sCMNDSV
				,@tNgayCapCMNDSV
				,@sNoiCapCMNDSV
				,@bHonNhanSV
				,@sNguoiLienHeSV
				,@sDiaChiNguoiLienHeSV
				,@sSdtNguoiLienHeSV
				,@iQuanHeVoiNguoiLienHeSV
				,@bKetnapDoanSV
				,@iNamketnapDoanSV
				,@sNoiketnapDoanSV
				,@iNamtotnghiepTHPTSV
				,@tNgayNhapHocSV
				,@tNgayRaTruongSV
				,@tNgayCapTheSV
				,@sLinkAvatarSV
				,@iTrangThaiSV
				)

END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_Login]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_Login]
			@sTendangnhapSV	varchar(50)
			,@sMatkhauSV	varchar(50)
			,@iTrangThaiSV	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaLop]
				, [PK_sMaSV]
				, [sHotenSV]
				, [sTendangnhapSV]
				, [sMatkhauSV]
				, [sEmailSV]
				, [sDiachiSV]
				, [sSdtSV]
				, [tNgaysinhSV]
				, [bGioitinhSV]
				, [sCMNDSV]
				, [tNgayCapCMNDSV]
				, [sNoiCapCMNDSV]
				, [bHonNhanSV]
				, [sNguoiLienHeSV]
				, [sDiaChiNguoiLienHeSV]
				, [sSdtNguoiLienHeSV]
				, [iQuanHeVoiNguoiLienHeSV]
				, [bKetnapDoanSV]
				, [iNamketnapDoanSV]
				, [sNoiketnapDoanSV]
				, [iNamtotnghiepTHPTSV]
				, [tNgayNhapHocSV]
				, [tNgayRaTruongSV]
				, [tNgayCapTheSV]
				, [sLinkAvatarSV]
				, [iTrangThaiSV]
	From	[tblSinhVien]
	Where
		([sTendangnhapSV] 	like @sTendangnhapSV)
		AND ([sMatkhauSV] 	like @sMatkhauSV)
		AND ([iTrangThaiSV] = @iTrangThaiSV)
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_ResetPassword]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_ResetPassword]
		@sTendangnhapSV	varchar(50)
		,@sMatkhauSV	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblSinhVien]	SET
		 [sTendangnhapSV] 	= @sTendangnhapSV
		,[sMatkhauSV] 	= @sMatkhauSV
	WHERE 
		[sTendangnhapSV] 	= @sTendangnhapSV
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_Search]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_Search]
			@FK_sMaLop	varchar(50)
			,@PK_sMaSV	varchar(50)
			,@sHotenSV	nvarchar(100)
			,@sTendangnhapSV	varchar(50)
			,@sMatkhauSV	varchar(50)
			,@sEmailSV	varchar(50)
			,@sDiachiSV	nvarchar(100)
			,@sSdtSV	varchar(13)
			,@tNgaysinhSV	datetime
			,@bGioitinhSV	bit
			,@sCMNDSV	varchar(9)
			,@tNgayCapCMNDSV	datetime
			,@sNoiCapCMNDSV	nvarchar(100)
			,@bHonNhanSV	bit
			,@sNguoiLienHeSV	nvarchar(100)
			,@sDiaChiNguoiLienHeSV	nvarchar(100)
			,@sSdtNguoiLienHeSV	varchar(13)
			,@iQuanHeVoiNguoiLienHeSV	smallint
			,@bKetnapDoanSV	bit
			,@iNamketnapDoanSV	smallint
			,@sNoiketnapDoanSV	nvarchar(100)
			,@iNamtotnghiepTHPTSV	smallint
			,@tNgayNhapHocSV	datetime
			,@tNgayRaTruongSV	datetime
			,@tNgayCapTheSV	datetime
			,@sLinkAvatarSV	varchar(200)
			,@iTrangThaiSV	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaLop]
				, [PK_sMaSV]
				, [sHotenSV]
				, [sTendangnhapSV]
				, [sMatkhauSV]
				, [sEmailSV]
				, [sDiachiSV]
				, [sSdtSV]
				, [tNgaysinhSV]
				, [bGioitinhSV]
				, [sCMNDSV]
				, [tNgayCapCMNDSV]
				, [sNoiCapCMNDSV]
				, [bHonNhanSV]
				, [sNguoiLienHeSV]
				, [sDiaChiNguoiLienHeSV]
				, [sSdtNguoiLienHeSV]
				, [iQuanHeVoiNguoiLienHeSV]
				, [bKetnapDoanSV]
				, [iNamketnapDoanSV]
				, [sNoiketnapDoanSV]
				, [iNamtotnghiepTHPTSV]
				, [tNgayNhapHocSV]
				, [tNgayRaTruongSV]
				, [tNgayCapTheSV]
				, [sLinkAvatarSV]
				, [iTrangThaiSV]
	From	[tblSinhVien]
	Where
		(@FK_sMaLop is null or [FK_sMaLop] 	like '%' + @FK_sMaLop+ '%')
		AND (@PK_sMaSV is null or [PK_sMaSV] 	like '%' + @PK_sMaSV+ '%')
		AND (@sHotenSV is null or [sHotenSV] 	like '%' + @sHotenSV+ '%')
		AND (@sTendangnhapSV is null or [sTendangnhapSV] 	like '%' + @sTendangnhapSV+ '%')
		AND (@sMatkhauSV is null or [sMatkhauSV] 	like '%' + @sMatkhauSV+ '%')
		AND (@sEmailSV is null or [sEmailSV] 	like '%' + @sEmailSV+ '%')
		AND (@sDiachiSV is null or [sDiachiSV] 	like '%' + @sDiachiSV+ '%')
		AND (@sSdtSV is null or [sSdtSV] 	like '%' + @sSdtSV+ '%')
		AND (@tNgaysinhSV is null or [tNgaysinhSV] 	= @tNgaysinhSV)
		AND (@bGioitinhSV is null or [bGioitinhSV] 	= @bGioitinhSV)
		AND (@sCMNDSV is null or [sCMNDSV] 	like '%' + @sCMNDSV+ '%')
		AND (@tNgayCapCMNDSV is null or [tNgayCapCMNDSV] 	= @tNgayCapCMNDSV)
		AND (@sNoiCapCMNDSV is null or [sNoiCapCMNDSV] 	like '%' + @sNoiCapCMNDSV+ '%')
		AND (@bHonNhanSV is null or [bHonNhanSV] = @bHonNhanSV)
		AND (@sNguoiLienHeSV is null or [sNguoiLienHeSV] 	like '%' + @sNguoiLienHeSV+ '%')
		AND (@sDiaChiNguoiLienHeSV is null or [sDiaChiNguoiLienHeSV] 	like '%' + @sDiaChiNguoiLienHeSV+ '%')
		AND (@sSdtNguoiLienHeSV is null or [sSdtNguoiLienHeSV] 	like '%' + @sSdtNguoiLienHeSV+ '%')
		AND (@iQuanHeVoiNguoiLienHeSV is null or [iQuanHeVoiNguoiLienHeSV] 	like '%' + @iQuanHeVoiNguoiLienHeSV+ '%')
		AND (@bKetnapDoanSV is null or [bKetnapDoanSV] 	= @bKetnapDoanSV)
		AND (@iNamketnapDoanSV is null or [iNamketnapDoanSV] 	like '%' + @iNamketnapDoanSV+ '%')
		AND (@sNoiketnapDoanSV is null or [sNoiketnapDoanSV] 	like '%' + @sNoiketnapDoanSV+ '%')
		AND (@iNamtotnghiepTHPTSV is null or [iNamtotnghiepTHPTSV] 	like '%' + @iNamtotnghiepTHPTSV+ '%')
		AND (@tNgayNhapHocSV is null or [tNgayNhapHocSV] 	= @tNgayNhapHocSV)
		AND (@tNgayRaTruongSV is null or [tNgayRaTruongSV] 	= @tNgayRaTruongSV)
		AND (@tNgayCapTheSV is null or [tNgayCapTheSV] 	= @tNgayCapTheSV)
		AND (@sLinkAvatarSV is null or [sLinkAvatarSV] 	like '%' + @sLinkAvatarSV+ '%')
		AND (@iTrangThaiSV is null or [iTrangThaiSV] 	like '%' + @iTrangThaiSV+ '%')
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_SelectByFK_sMaLop]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	
CREATE PROCEDURE [dbo].[tblSinhVien_SelectByFK_sMaLop]
		@FK_sMaLop	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_sMaLop]
				, [PK_sMaSV]
				, [sHotenSV]
				, [sTendangnhapSV]
				, [sMatkhauSV]
				, [sEmailSV]
				, [sDiachiSV]
				, [sSdtSV]
				, [tNgaysinhSV]
				, [bGioitinhSV]
				, [sCMNDSV]
				, [tNgayCapCMNDSV]
				, [sNoiCapCMNDSV]
				, [bHonNhanSV]
				, [sNguoiLienHeSV]
				, [sDiaChiNguoiLienHeSV]
				, [sSdtNguoiLienHeSV]
				, [iQuanHeVoiNguoiLienHeSV]
				, [bKetnapDoanSV]
				, [iNamketnapDoanSV]
				, [sNoiketnapDoanSV]
				, [iNamtotnghiepTHPTSV]
				, [tNgayNhapHocSV]
				, [tNgayRaTruongSV]
				, [tNgayCapTheSV]
				, [sLinkAvatarSV]
				, [iTrangThaiSV]
	From	[tblSinhVien]
	Where	FK_sMaLop	= @FK_sMaLop
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_SelectBysEmailSVvssSdtSV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_SelectBysEmailSVvssSdtSV]
		@sEmailSV	varchar(50)
		,@sSdtSV	varchar(13)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaLop]
				, [PK_sMaSV]
				, [sHotenSV]
				, [sTendangnhapSV]
				, [sMatkhauSV]
				, [sEmailSV]
				, [sDiachiSV]
				, [sSdtSV]
				, [tNgaysinhSV]
				, [bGioitinhSV]
				, [sCMNDSV]
				, [tNgayCapCMNDSV]
				, [sNoiCapCMNDSV]
				, [bHonNhanSV]
				, [sNguoiLienHeSV]
				, [sDiaChiNguoiLienHeSV]
				, [sSdtNguoiLienHeSV]
				, [iQuanHeVoiNguoiLienHeSV]
				, [bKetnapDoanSV]
				, [iNamketnapDoanSV]
				, [sNoiketnapDoanSV]
				, [iNamtotnghiepTHPTSV]
				, [tNgayNhapHocSV]
				, [tNgayRaTruongSV]
				, [tNgayCapTheSV]
				, [sLinkAvatarSV]
				, [iTrangThaiSV]
	From	[tblSinhVien]
	Where
		sEmailSV like @sEmailSV
		AND sSdtSV like @sSdtSV
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_SelectBysTendangnhapSV]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_SelectBysTendangnhapSV]
		@sTendangnhapSV	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaLop]
				, [PK_sMaSV]
				, [sHotenSV]
				, [sTendangnhapSV]
				, [sMatkhauSV]
				, [sEmailSV]
				, [sDiachiSV]
				, [sSdtSV]
				, [tNgaysinhSV]
				, [bGioitinhSV]
				, [sCMNDSV]
				, [tNgayCapCMNDSV]
				, [sNoiCapCMNDSV]
				, [bHonNhanSV]
				, [sNguoiLienHeSV]
				, [sDiaChiNguoiLienHeSV]
				, [sSdtNguoiLienHeSV]
				, [iQuanHeVoiNguoiLienHeSV]
				, [bKetnapDoanSV]
				, [iNamketnapDoanSV]
				, [sNoiketnapDoanSV]
				, [iNamtotnghiepTHPTSV]
				, [tNgayNhapHocSV]
				, [tNgayRaTruongSV]
				, [tNgayCapTheSV]
				, [sLinkAvatarSV]
				, [iTrangThaiSV]
	From	[tblSinhVien]
	Where
		[sTendangnhapSV] 	= @sTendangnhapSV
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_SelectItem]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_SelectItem]
		@PK_sMaSV	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaLop]
				, [PK_sMaSV]
				, [sHotenSV]
				, [sTendangnhapSV]
				, [sMatkhauSV]
				, [sEmailSV]
				, [sDiachiSV]
				, [sSdtSV]
				, [tNgaysinhSV]
				, [bGioitinhSV]
				, [sCMNDSV]
				, [tNgayCapCMNDSV]
				, [sNoiCapCMNDSV]
				, [bHonNhanSV]
				, [sNguoiLienHeSV]
				, [sDiaChiNguoiLienHeSV]
				, [sSdtNguoiLienHeSV]
				, [iQuanHeVoiNguoiLienHeSV]
				, [bKetnapDoanSV]
				, [iNamketnapDoanSV]
				, [sNoiketnapDoanSV]
				, [iNamtotnghiepTHPTSV]
				, [tNgayNhapHocSV]
				, [tNgayRaTruongSV]
				, [tNgayCapTheSV]
				, [sLinkAvatarSV]
				, [iTrangThaiSV]
	From	[tblSinhVien]
	Where
		[PK_sMaSV] 	= @PK_sMaSV
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_SelectList]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_SelectList]
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaLop]
				, [PK_sMaSV]
				, [sHotenSV]
				, [sTendangnhapSV]
				, [sMatkhauSV]
				, [sEmailSV]
				, [sDiachiSV]
				, [sSdtSV]
				, [tNgaysinhSV]
				, [bGioitinhSV]
				, [sCMNDSV]
				, [tNgayCapCMNDSV]
				, [sNoiCapCMNDSV]
				, [bHonNhanSV]
				, [sNguoiLienHeSV]
				, [sDiaChiNguoiLienHeSV]
				, [sSdtNguoiLienHeSV]
				, [iQuanHeVoiNguoiLienHeSV]
				, [bKetnapDoanSV]
				, [iNamketnapDoanSV]
				, [sNoiketnapDoanSV]
				, [iNamtotnghiepTHPTSV]
				, [tNgayNhapHocSV]
				, [tNgayRaTruongSV]
				, [tNgayCapTheSV]
				, [sLinkAvatarSV]
				, [iTrangThaiSV]
	From	[tblSinhVien]
	Order by [PK_sMaSV]
		
END


GO
/****** Object:  StoredProcedure [dbo].[tblSinhVien_Update]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	28/03/2014 21:16
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE [dbo].[tblSinhVien_Update]
		@FK_sMaLop	varchar(50)
		,@PK_sMaSV	varchar(50)
		,@sHotenSV	nvarchar(100)
		,@sTendangnhapSV	varchar(50)
		,@sMatkhauSV	varchar(50)
		,@sEmailSV	varchar(50)
		,@sDiachiSV	nvarchar(100)
		,@sSdtSV	varchar(13)
		,@tNgaysinhSV	datetime
		,@bGioitinhSV	bit
		,@sCMNDSV	varchar(9)
		,@tNgayCapCMNDSV	datetime
		,@sNoiCapCMNDSV	nvarchar(100)
		,@bHonNhanSV	bit
		,@sNguoiLienHeSV	nvarchar(100)
		,@sDiaChiNguoiLienHeSV	nvarchar(100)
		,@sSdtNguoiLienHeSV	varchar(13)
		,@iQuanHeVoiNguoiLienHeSV	smallint
		,@bKetnapDoanSV	bit
		,@iNamketnapDoanSV	smallint
		,@sNoiketnapDoanSV	nvarchar(100)
		,@iNamtotnghiepTHPTSV	smallint
		,@tNgayNhapHocSV	datetime
		,@tNgayRaTruongSV	datetime
		,@tNgayCapTheSV	datetime
		,@sLinkAvatarSV	varchar(200)
		,@iTrangThaiSV	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblSinhVien]	SET
		 [FK_sMaLop] 	= @FK_sMaLop
		,[sHotenSV] 	= @sHotenSV
		,[sTendangnhapSV] 	= @sTendangnhapSV
		,[sMatkhauSV] 	= @sMatkhauSV
		,[sEmailSV] 	= @sEmailSV
		,[sDiachiSV] 	= @sDiachiSV
		,[sSdtSV] 	= @sSdtSV
		,[tNgaysinhSV] 	= @tNgaysinhSV
		,[bGioitinhSV] 	= @bGioitinhSV
		,[sCMNDSV] 	= @sCMNDSV
		,[tNgayCapCMNDSV] 	= @tNgayCapCMNDSV
		,[sNoiCapCMNDSV] 	= @sNoiCapCMNDSV
		,[bHonNhanSV] 	= @bHonNhanSV
		,[sNguoiLienHeSV] 	= @sNguoiLienHeSV
		,[sDiaChiNguoiLienHeSV] 	= @sDiaChiNguoiLienHeSV
		,[sSdtNguoiLienHeSV] 	= @sSdtNguoiLienHeSV
		,[iQuanHeVoiNguoiLienHeSV] 	= @iQuanHeVoiNguoiLienHeSV
		,[bKetnapDoanSV] 	= @bKetnapDoanSV
		,[iNamketnapDoanSV] 	= @iNamketnapDoanSV
		,[sNoiketnapDoanSV] 	= @sNoiketnapDoanSV
		,[iNamtotnghiepTHPTSV] 	= @iNamtotnghiepTHPTSV
		,[tNgayNhapHocSV] 	= @tNgayNhapHocSV
		,[tNgayRaTruongSV] 	= @tNgayRaTruongSV
		,[tNgayCapTheSV] 	= @tNgayCapTheSV
		,[sLinkAvatarSV] 	= @sLinkAvatarSV
		,[iTrangThaiSV] 	= @iTrangThaiSV
	WHERE 
		[PK_sMaSV] 	= @PK_sMaSV
		
END


GO
/****** Object:  StoredProcedure [dbo].[UpdateSiSo]    Script Date: 06/04/2014 15:52:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[UpdateSiSo]
@PK_sMaLop varchar(50)
AS
BEGIN
UPDATE tblLopHoc	SET
	iSiso 	= (SELECT count(PK_sMaSV) from tblSinhVien where FK_sMaLop = @PK_sMaLop)
WHERE PK_sMalop = @PK_sMaLop
END
GO
