
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblBaiViet_Update
		@FK_sMaGV	varchar(50)
		,@PK_lMaBaiViet	bigint
		,@sTieuDe	nvarchar(500)
		,@sLinkAnh	varchar(200)
		,@sTag	nvarchar(500)
		,@sNoiDung	nvarchar(max)
		,@iLuotXem	int
		,@tNgayViet	datetime
		,@tNgayCapNhat	datetime
		,@sMoTa	nvarchar(200)
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblBaiViet]	SET
		 [FK_sMaGV] 	= @FK_sMaGV
		,[sTieuDe] 	= @sTieuDe
		,[sLinkAnh] 	= @sLinkAnh
		,[sTag] 	= @sTag
		,[sNoiDung] 	= @sNoiDung
		,[iLuotXem] 	= @iLuotXem
		,[tNgayViet] 	= @tNgayViet
		,[tNgayCapNhat] 	= @tNgayCapNhat
		,[sMoTa] 	= @sMoTa
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_lMaBaiViet] 	= @PK_lMaBaiViet
		
END

GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblBaiViet_Delete
		@PK_lMaBaiViet	bigint
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblBaiViet]
	Where
		[PK_lMaBaiViet] 	= @PK_lMaBaiViet
		
END

GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblBaiViet_Insert
			@FK_sMaGV	varchar(50)
			,@PK_lMaBaiViet	bigint
			,@sTieuDe	nvarchar(500)
			,@sLinkAnh	varchar(200)
			,@sTag	nvarchar(500)
			,@sNoiDung	nvarchar(max)
			,@iLuotXem	int
			,@tNgayViet	datetime
			,@tNgayCapNhat	datetime
			,@sMoTa	nvarchar(200)
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblBaiViet]( [FK_sMaGV]
				,[PK_lMaBaiViet]
				,[sTieuDe]
				,[sLinkAnh]
				,[sTag]
				,[sNoiDung]
				,[iLuotXem]
				,[tNgayViet]
				,[tNgayCapNhat]
				,[sMoTa]
				,[iTrangThai]
				)
		
	Values	( @FK_sMaGV
				,@PK_lMaBaiViet
				,@sTieuDe
				,@sLinkAnh
				,@sTag
				,@sNoiDung
				,@iLuotXem
				,@tNgayViet
				,@tNgayCapNhat
				,@sMoTa
				,@iTrangThai
				)

END

GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblBaiViet_SelectItem
		@PK_lMaBaiViet	bigint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaGV]
				, [PK_lMaBaiViet]
				, [sTieuDe]
				, [sLinkAnh]
				, [sTag]
				, [sNoiDung]
				, [iLuotXem]
				, [tNgayViet]
				, [tNgayCapNhat]
				, [sMoTa]
				, [iTrangThai]
	From	[tblBaiViet]
	Where
		[PK_lMaBaiViet] 	= @PK_lMaBaiViet
		
END

GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblBaiViet_SelectList
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaGV]
				, [PK_lMaBaiViet]
				, [sTieuDe]
				, [sLinkAnh]
				, [sTag]
				, [sNoiDung]
				, [iLuotXem]
				, [tNgayViet]
				, [tNgayCapNhat]
				, [sMoTa]
				, [iTrangThai]
	From	[tblBaiViet]
	Order by [PK_lMaBaiViet]
		
END

GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblBaiViet_Search
			@FK_sMaGV	varchar(50)
			,@PK_lMaBaiViet	bigint
			,@sTieuDe	nvarchar(500)
			,@sLinkAnh	varchar(200)
			,@sTag	nvarchar(500)
			,@sNoiDung	nvarchar(max)
			,@iLuotXem	int
			,@tNgayViet	datetime
			,@tNgayCapNhat	datetime
			,@sMoTa	nvarchar(200)
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[FK_sMaGV]
				, [PK_lMaBaiViet]
				, [sTieuDe]
				, [sLinkAnh]
				, [sTag]
				, [sNoiDung]
				, [iLuotXem]
				, [tNgayViet]
				, [tNgayCapNhat]
				, [sMoTa]
				, [iTrangThai]
	From	[tblBaiViet]
	Where
		(@FK_sMaGV is null or [FK_sMaGV] 	like '%' + @FK_sMaGV+ '%')
		AND (@PK_lMaBaiViet is null or [PK_lMaBaiViet] 	like '%' + @PK_lMaBaiViet+ '%')
		AND (@sTieuDe is null or [sTieuDe] 	like '%' + @sTieuDe+ '%')
		AND (@sLinkAnh is null or [sLinkAnh] 	like '%' + @sLinkAnh+ '%')
		AND (@sTag is null or [sTag] 	like '%' + @sTag+ '%')
		AND (@sNoiDung is null or [sNoiDung] 	like '%' + @sNoiDung+ '%')
		AND (@iLuotXem is null or [iLuotXem] 	= @iLuotXem)
		AND (@tNgayViet is null or [tNgayViet] 	= @tNgayViet)
		AND (@tNgayCapNhat is null or [tNgayCapNhat] 	= @tNgayCapNhat)
		AND (@sMoTa is null or [sMoTa] 	like '%' + @sMoTa+ '%')
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END

GO

	
CREATE PROCEDURE tblBaiViet_SelectByFK_sMaGV
		@FK_sMaGV	varchar
AS
BEGIN
	SET NOCOUNT ON;

	Select 		[FK_sMaGV]
				, [PK_lMaBaiViet]
				, [sTieuDe]
				, [sLinkAnh]
				, [sTag]
				, [sNoiDung]
				, [iLuotXem]
				, [tNgayViet]
				, [tNgayCapNhat]
				, [sMoTa]
				, [iTrangThai]
	From	[tblBaiViet]
	Where	FK_sMaGV	= @FK_sMaGV
END

GO
	