function Lrequest(lr_url,ctCall,imgCall,$){this.url_request="http://quick-upload.apps.zing.vn";this.link={};this.ltmp={};var self=this;this.log=function(){},this.parse=function(data){if(lr_url!=""){this.link.domain=this.gDomain(lr_url);this.link.gurl=this.gUrl(lr_url);var vfile=this.testFile(lr_url);if(vfile!="")var data=vfile;var url_request=this.url_request+"/index.php?type=request&url="+encodeURIComponent(lr_url)+"&jsonpcallback=?";if(typeof data!="undefined")this.parseCB({data:data,zmt:1});else $.getJSON(url_request,
this.parseCB)}},this.parseCB=function(rsp){if(typeof rsp.data!="undefined"&&data!=""){var data=rsp.data.replace(/(\r\n|\r|\n)/gi,"").replace(/<script.*?>.*?<\/script>/ig,"").replace(/<style.*?>.*?<\/style>/ig,"");var match=data.match(/<base.*?href="(.*?)".*?>/i);if(match!=null&&typeof match[1]!="undefined")self.ltmp.base=self.gDomain(match[1]);self.link.title=self.gTitle(data);self.link.desc=self.gDesc(data);self.link.images=[];self.makeMCode(data);if(self.link.code=="")self.link.images=self.gImages(data);
self.ltmp.cur_ind=0;self.ltmp.img_arr=[];if(typeof ctCall=="function")ctCall.call(null,self.link);if(self.link.images.length==1){if(typeof imgCall=="function")imgCall.call(null,self.link.images,1)}else if(typeof rsp.zmt!="undefined")self.imgLocal();else self.imgLoader()}else{ctCall.call(null,self.link);imgCall.call(null,[],1)}},this.testFile=function(surl){var pos=surl.search(/\.(gif|jpg|jpeg|png)$/i);if(pos>0)return'<img src="'+surl+'">';return""},this.rmTag=function(data){return data.replace(/<.*?>/ig,
"")},this.imgChain=function(){if(this.width>=80&&this.height>=80){self.ltmp.img_arr.push(self.link.images[self.ltmp.cur_ind]);if(typeof imgCall=="function")imgCall.call(null,self.ltmp.img_arr,0)}self.ltmp.cur_ind+=1;if(self.ltmp.cur_ind<self.link.images.length)self.imgLoader();else if(typeof imgCall=="function")imgCall.call(null,self.ltmp.img_arr,1)},this.imgLocal=function(){for(var i in self.link.images){var img=new Image;img.setAttribute("src",self.link.images[i]);if(img.width>=80&&img.height>=
80)self.ltmp.img_arr.push(self.link.images[i])}imgCall.call(null,self.ltmp.img_arr,1)},this.imgLoader=function(){var img=new Image;img.setAttribute("src",self.link.images[self.ltmp.cur_ind]);img.onerror=self.imgChain;img.onload=self.imgChain},this.gUrl=function(surl){var url=surl;var fpos=surl.lastIndexOf("/");if(fpos!=-1)url=surl.substr(0,fpos);return url},this.gDomain=function(surl){var domain=surl.substr(7);var fpos=domain.indexOf("/");if(fpos!=-1)domain=domain.substr(0,fpos);return domain},this.gTitle=
function(data){var title="";var matches=data.match(/<title.*?>\s*(.*?)\s*<\/title.*?>/i);if(matches!=null)title=typeof matches[1]!="undefined"?matches[1]:"";return title},this.gDesc=function(data){var desc="";var matches=data.match(/<meta[^\<\>]*?description.*?>/i);if(matches!=null){matches=matches[0].match(/content=(.*?)>/i);if(matches!=null&&typeof matches[1]!="undefined")desc=matches[1];var matches=matches[1].match(/["']\s*(.*?)\s*["']/i);if(matches!=null&&typeof matches[1]!="undefined")desc=matches[1]}var descl=
desc.length;if(desc==""||descl>350){matches=data.match(/<(p|h2).*?>.*?<\/\1>/ig);if(matches!=null){var _matches,desctmp="";for(var i in matches){_matches=(matches[i]+"").match(/<.*?>\s*(.+?)\s*?</i);if(_matches!=null&&typeof _matches[1]!="undefined"){desctmp=this.rmTag(_matches[1]);desctmp=desctmp||desc;if(desctmp.length>=100){desc=desctmp;break}}}}}desc=desc.split(/(?:&nbsp;|\s)/i).slice(0,100);return desc.join(" ")},this.gImages=function(data){var images=[];var matches=data.match(/<img.*?src=["']?.*?["']?.*?>/gi);
if(matches!=null&&matches.length)for(var i=0;i<matches.length;i++){var matches2=matches[i].match(/src=["'](.*?)["']/i);if(matches2!=null&&typeof matches2[1]!="undefined"&&matches2[1].indexOf(".gif")==-1)if(/(http|https|ftp)\:\/\//.test(matches2[1]))images.push(matches2[1]);else if(typeof self.ltmp.base!="undefined")images.push("http://"+self.ltmp.base+matches2[1]);else if(matches2[1].indexOf("/")==-1)images.push(self.link.gurl+"/"+matches2[1]);else images.push("http://"+self.link.domain+matches2[1])}return images},
this.makeMCode=function(data){var code="";var m_width=0;var m_height=0;var matches=data.match(/<link[^\<\>]*?video_src.*?>/i);if(matches!=null){matches=matches[0].match(/href=["'](.*?)["']/i);if(matches!=null&&typeof matches[1]!="undefined")code=matches[1]}matches=data.match(/<link[^\<\>]*?image_src.*?>/i);if(matches!=null){matches=matches[0].match(/href=["'](.*?)["']/i);if(matches!=null&&typeof matches[1]!="undefined")this.link.images.push(matches[1])}matches=data.match(/<meta [^\<\>]*?video_width.*?>/i);
if(matches!=null){matches=matches[0].match(/content=["']?(\d+)["']?/i);if(matches!=null&&typeof matches[1]!="undefined")m_width=matches[1]}matches=data.match(/<meta [^\<\>]*?video_height.*?>/i);if(matches!=null){matches=matches[0].match(/content=["']?(\d+)["']?/i);if(matches!=null&&typeof matches[1]!="undefined")m_height=matches[1]}if(code==""){var matches=data.match(/<meta[^\<\>]*?og\:(video|audio).*?>/i);if(matches!=null){matches=matches[0].match(/content=["'](.*?)["']/i);if(matches!=null&&typeof matches[1]!=
"undefined")code=matches[1]}matches=data.match(/<meta[^\<\>]*?og\:image.*?>/i);if(matches!=null){matches=matches[0].match(/content=["'](.*?)["']/i);if(matches!=null&&typeof matches[1]!="undefined")this.link.images.push(matches[1])}matches=data.match(/<meta[^\<\>]*?og\:video\:width.*?>/i);if(matches!=null){matches=matches[0].match(/content=["']?(\d+)["']?/i);if(matches!=null&&typeof matches[1]!="undefined")m_width=matches[1]}matches=data.match(/<meta[^\<\>]*?og\:video\:height.*?>/i);if(matches!=null){matches=
matches[0].match(/content=["']?(\d+)["']?/i);if(matches!=null&&typeof matches[1]!="undefined")m_height=matches[1]}}this.link.code=code;this.link.width=m_width;this.link.height=m_height}};
