
-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblMonHoc_Update
		@PK_sMaMonhoc	varchar(50)
		,@sTenMonhoc	nvarchar(100)
		,@iSotrinh	smallint
		,@iSotietday	smallint
		,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	UPDATE [tblMonHoc]	SET
		 [sTenMonhoc] 	= @sTenMonhoc
		,[iSotrinh] 	= @iSotrinh
		,[iSotietday] 	= @iSotietday
		,[iTrangThai] 	= @iTrangThai
	WHERE 
		[PK_sMaMonhoc] 	= @PK_sMaMonhoc
		
END

GO

-- =============================================
-- This stored procedure is generated by BuildProject 
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblMonHoc_Delete
		@PK_sMaMonhoc	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Delete [tblMonHoc]
	Where
		[PK_sMaMonhoc] 	= @PK_sMaMonhoc
		
END

GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblMonHoc_Insert
			@PK_sMaMonhoc	varchar(50)
			,@sTenMonhoc	nvarchar(100)
			,@iSotrinh	smallint
			,@iSotietday	smallint
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Insert Into [tblMonHoc]( [PK_sMaMonhoc]
				,[sTenMonhoc]
				,[iSotrinh]
				,[iSotietday]
				,[iTrangThai]
				)
		
	Values	( @PK_sMaMonhoc
				,@sTenMonhoc
				,@iSotrinh
				,@iSotietday
				,@iTrangThai
				)

END

GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblMonHoc_SelectItem
		@PK_sMaMonhoc	varchar(50)
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaMonhoc]
				, [sTenMonhoc]
				, [iSotrinh]
				, [iSotietday]
				, [iTrangThai]
	From	[tblMonHoc]
	Where
		[PK_sMaMonhoc] 	= @PK_sMaMonhoc
		
END

GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblMonHoc_SelectList
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaMonhoc]
				, [sTenMonhoc]
				, [iSotrinh]
				, [iSotietday]
				, [iTrangThai]
	From	[tblMonHoc]
	Order by [PK_sMaMonhoc]
		
END

GO

-- =============================================
-- This stored procedure is generated by BuildProject
-- Author:	ThangNM
-- Create date:	16/03/2014 16:44
-- Description:	
-- Revise History:	
-- =============================================
CREATE PROCEDURE tblMonHoc_Search
			@PK_sMaMonhoc	varchar(50)
			,@sTenMonhoc	nvarchar(100)
			,@iSotrinh	smallint
			,@iSotietday	smallint
			,@iTrangThai	smallint
AS
BEGIN
	SET NOCOUNT ON;
		
	Select 		[PK_sMaMonhoc]
				, [sTenMonhoc]
				, [iSotrinh]
				, [iSotietday]
				, [iTrangThai]
	From	[tblMonHoc]
	Where
		(@PK_sMaMonhoc is null or [PK_sMaMonhoc] 	like '%' + @PK_sMaMonhoc+ '%')
		AND (@sTenMonhoc is null or [sTenMonhoc] 	like '%' + @sTenMonhoc+ '%')
		AND (@iSotrinh is null or [iSotrinh] 	like '%' + @iSotrinh+ '%')
		AND (@iSotietday is null or [iSotietday] 	like '%' + @iSotietday+ '%')
		AND (@iTrangThai is null or [iTrangThai] 	like '%' + @iTrangThai+ '%')
		
END

GO

	