//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_TN.Test {
    
    
    public partial class TPhanCongCongTac {
        
        /// <summary>
        /// PhanCongCongTac_DetailUC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DO_AN_TN.UserControl.PhanCongCongTac_DetailUC PhanCongCongTac_DetailUC1;
        
        /// <summary>
        /// PhanCongCongTac_ListUC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DO_AN_TN.UserControl.PhanCongCongTac_ListUC PhanCongCongTac_ListUC1;
    }
}
